# Encrypt before committing: sops --encrypt --in-place secret.sops.yaml
# Generate htpasswd entries with: htpasswd -nB <devicename>
# All repos must be initialized with the same restic-password value below.
apiVersion: v1
kind: Secret
metadata:
    name: restic-rest-server-secret
stringData:
    #ENC[AES256_GCM,data:ASg1PHrtJqWTxT0nwFgGX65qiqVj9f9JkfXi4NRFXuqk9mxNIUxid9STnURyKfIsdT9aAk0=,iv:MsD6OAH5ONoNWjEtHaVOWBJw5sIi+acSGf2rRGmnsOI=,tag:ltFsOqV7sUgMR88iR1ELDw==,type:comment]
    .htpasswd: ENC[AES256_GCM,data:N3oQ35/KM8UrFzLHLI+JtpUz5HXwvDIiJM0Fy8fzyZwjKvQnO3J23AeSTdmkq3K1dQ76poJN0gRvTo0VAwrjbxXqweAx7MKXCvt+T3mtYaaOGMwsDBZFRWb0ohApt3Vpx8I1A0wrMiFRiqoTSOh+vEJq72RvDO3sE0HxBKCuzjHIQXiFdI+O12jDI/UIkO4PG4N0cud/,iv:dMT4yfuT+qQxZ0LtpdbXGp1sGSjF5VzAFEott/HBQAY=,tag:MGZABhX66qo3mAhPxSHAYQ==,type:str]
    #ENC[AES256_GCM,data:pcNxJBbcQQynqtainCM0IEud1QsmzEFYyy2XaNDruj5Ht8VS38OQ/b++Q3874ugFTdiUy6eLngfJ7IcGKmPjSqKpHhwuSQ0W6YZL4i6H76cyUJysoYU=,iv:vaiWKL8+oIEtBS1lxiNJVkciiPAP1whRLHKv/LqD+tU=,tag:jVKJ0cJW1AfrO3LvPQheFQ==,type:comment]
    restic-password: ENC[AES256_GCM,data:0VVSbKAdoYQSA/W38SumIUuNd9kRgsQc889yhiBTa5BAGrzJKALBHa3HNVI=,iv:xD9EJ+TxsPan5Ws6j+r9vglIemRGn6Zf+7J8l+YoOr0=,tag:kW6BLr2fJ02CImIF4GULUQ==,type:str]
sops:
    age:
        - recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5US9hOTAyV29DOEJJcjhF
            WWN5OHRoWFpscHk5TVhZNFFHSVNFcy9pTVQ0CkRLc2RpbUZwYVd6Y2p6UDRWelFB
            bUU1eVQvQlYrUEdrWFY5QzVSZXNKYUUKLS0tIHlRbUFKTzhyQjB0M1hhMlJ2aCtN
            OWdXaENXaDZzaFcrWTA5UXBPN0wxR1UKTf8yz2KjkW+Z9hu6bYeSfdegP95qk1cV
            gyYQ5ytyWC6Q13yaqoLLolPyJYxOpNorsTnzENQ2LYd8r3EqmOpKmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T23:08:15Z"
    mac: ENC[AES256_GCM,data:CABm4srqlwbYOt4KE9VYkDIPD9RYYDcvnZIYEPfwycBxXUju0QlwiX2045zLdosYrgzAtYRcXO6JbFlHplzTGdqYIM5YrmyfEXtn6xgAvuOCSkw+CRbXXqxUAW6SppDF05i+9TDrzHwrtDnOpa86lIVUZuegfbr0T8D7zi4jhKA=,iv:UlAZt7OUUipBDg47jRXvheEsP5JX07cJJxI6m5qat+8=,tag:kZJhK2R8pQsK7cDvDj1zoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
