# Encrypt before committing: sops --encrypt --in-place secret.sops.yaml
# Generate htpasswd entries with: htpasswd -nB <devicename>
# All repos must be initialized with the same restic-password value below.
apiVersion: v1
kind: Secret
metadata:
    name: restic-rest-server-secret
stringData:
    #ENC[AES256_GCM,data:geZuV7bATUq53p+juVtsp09Fz3La7RPQ7J2DFgy61wIVtcNn8N78L27tSPoC7k7EFF4J8jA=,iv:uHoBgpCHRQ/dV8KE9/LlbpDw84YK1dGUSqfjQ0KLJs4=,tag:uWHVRlN7YuUlJleCU2SHSg==,type:comment]
    .htpasswd: ENC[AES256_GCM,data:zTR9t/J/jUbCuXKEJrNmfJ3S2DT+PC4y0Wu8GhTZjq9ETDVL5WuHjXKzFy0Om5akjPB2foW6GhB/+Jom2b/pmy1GAVRlJgpFmTdcDoH4,iv:im3bveRPKdhIVR4SjDIkT2P2m6MOyogOvOPWwLVQFqQ=,tag:TI3LDYYFcLlXPRfKxE+sMA==,type:str]
    #ENC[AES256_GCM,data:QUMi42P6SaBQVH0nuJSQDYgW6KgIrQJoM15Kh0CLBjbvD5WG1vey/3ylai4PDbHmHbsZKdR3YUl2+nzwPGCvmRZaBZorqcn8/GvHuFuh2HhTm+CIUsA=,iv:i5H9SUOZRbPwZ+xwlRyY9TfcwBR+jjvT/yjwFj66/Rk=,tag:yw0+vJhiQAOKB3z9EGdmZA==,type:comment]
    restic-password: ENC[AES256_GCM,data:1Z9PTGoO4nbxbcOz+lFBlSJTJ3unwimiRjI++/UhSw72PaHns9mSi5ZgY40=,iv:xq6BttYYF2if0wkMwV2WCqDZnK8Ik4oDyiwxyZ6+/Ko=,tag:dU6iW+691bSAw8Z/9scWTg==,type:str]
sops:
    age:
        - recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcC80NzRtcGVjV1lUaGw5
            OERVS1NYRjJYbk41WHJhc1ROM01CYmI2OXpzCmZBd1BIYWlxQWpPSUlySm0ya05y
            UHdyTDNVb1A0b2J6RjRZNHN4eUZsZEUKLS0tIHR0eWo1dXF2Q1dEejM1OHNJQU5E
            ZnAyL0RIS0d1cXVSSUVVWjd5R0t2T2cKxa26w/GkjYL4azv/W04C9h0FQAXyhZDd
            Rs/QGwdaWpoxylzIVEhU0pxJNJQYE7A8wHjl6+j9U7E9Ul+iC+VGvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T17:45:45Z"
    mac: ENC[AES256_GCM,data:I4WXHFFXvruCuGUW5JJ7uHiFgtvJQj4zfDnm2G07yQMF4zozJDSpem8TTh9gUsQ9Dp+ChSE6fqgXcgmWGV6URKEhEoYuvceTgSMrZjdAGfVAGUDpH+/lvpAO1zd5vNfBPuRtu6koR2EAzC32So+csmzxODYeaus7eUEuqyeuUeM=,iv:Sq5sFV/YaCUygK6tzEUqOfIeO8goQeI/NK695simBdo=,tag:AnW4bYBBbG8jNjwGYVY6uQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
