# Encrypt before committing: sops --encrypt --in-place secret.sops.yaml
# Generate htpasswd entries with: htpasswd -nB <devicename>
# All repos must be initialized with the same restic-password value below.
apiVersion: v1
kind: Secret
metadata:
    name: restic-rest-server-secret
stringData:
    #ENC[AES256_GCM,data:aouG9whJ2fguZwZq6PKNHdRVmjC2fTQzYoigfbG+ylvHCIJyZulAiZkw6qSXexIrvmvZHxY=,iv:PBM0ZdmP5p3fH+eHQfOGNHkF+OLJlozVsldKaHZa+3Q=,tag:Fk65sBDYMrnmIyQBN+OUGw==,type:comment]
    .htpasswd: ENC[AES256_GCM,data:BmGa1VLysSoYwXykjSZrYltNdYFP20Tv45WGzMQ46Zwf3b0fEBUx6VNPDYe7c5aVE0VOZ5z7BkfLPI+yp63YgKD27HrV3lSV0jCyRWHg,iv:rFB/tMhmMwXXyY37zqDNipyfOHwfBj8HLXqiRY290ts=,tag:WHU9XFslR11AQl7ntK+k5A==,type:str]
    #ENC[AES256_GCM,data:BMwrv6oRRAnK/hEbcIriaVKERGhgRRf8Ke+RaibQJVIT0K5zTK0JyfhZnzQP9TsRBn0mRRzSWtpszN2pvXzBmiX6X6pPrRdkFdI7f8JXRtqLRrIBcHA=,iv:yqNtYfUesHzxq5iNzWnDOkinKloi9IjrwW6ZSJoNz7k=,tag:coV8z8SlVJMrzcm/oQ+7lg==,type:comment]
    restic-password: ENC[AES256_GCM,data:vZNxaYhJF8fW99y6UmWdesIdPr5Gi0+iKpb03+MhxQvBA9hgEOurPHJS3/Y=,iv:iiHK7GrZjLIChcZr20KGs+cFzLb1wq9tL0hlEHOtHs0=,tag:S7HcEDJ4OIaeLCvvBjcdIQ==,type:str]
sops:
    age:
        - recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWVHWnRRSGdmNjQvWjA0
            WStUL2pxME00emxkckhQcHlyb2hza0s1QUJNCkp3dEtQNVZkeldBNWEzQ2hoYjFT
            MkRFWGNMeTk3Z1UwSVlsL1krZmYvc3cKLS0tIDZadzhoWS9NVWtPc1BTdkkwQUdo
            ejV4dTVsc0ZseE8vNGNCK3R0dnVucE0Ku3bJtN/A9XkCQJK4hI/euwxjAExLh8ds
            aGuwH93WI3KyhVz8UEw7G/bTCYBQUJNOBFs7ZKWxMPVx8ZBZF9G7Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T18:27:32Z"
    mac: ENC[AES256_GCM,data:uhs0IiRd+khh4AkPe0JNV/VUIsdm9igv7X6H5cAmKhj6RIspeDA9bQLnBFycDJ0FrzG45qowlJXhHvyAyFSNjehej+/m92RMWT7A5kkSbMuhnY/V+/ki4lMWDQdgN3qUxgYWB+L7GgDyIXs0xkIfuqf8Jq3s5uxsRBdt3qjkB8s=,iv:0r8x00PciGSSvrtG5b/dfKhwH7ynU5KmFyk6qOlsScc=,tag:gGz3bvjaCvervRLRvzKONg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
