{
 "title": "FRPS",
 "description": "This Grafana monitoring panel is designed for the frp project, aiming to monitor the connection count, proxy count, and traffic data of frp servers. The panel provides intuitive charts and data to help users understand the real-time operational status and performance metrics of frp servers.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "NODE",
    "query": {
     "query": "label_values(frp_server_client_counts,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (frp_server_client_counts)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (frp_server_connection_counts)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (rate(frp_server_traffic_in[1m])) / 60 * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (rate(frp_server_traffic_out[1m])) / 60 * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (frp_server_traffic_in)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (frp_server_traffic_out)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Details <$NODE>", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "NODE" },
  {
   "title": "Total Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frp_server_client_counts{instance=\"$NODE\"}",
     "legendFormat": "Client Connections <{{instance}}>"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (frp_server_connection_counts{type=\"tcp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (frp_server_traffic_out{type=\"tcp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (frp_server_connection_counts{type=\"http\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (frp_server_traffic_out{type=\"http\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STCP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (frp_server_connection_counts{type=\"stcp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (frp_server_traffic_out{type=\"stcp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tunnels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(frp_server_proxy_counts{instance=\"$NODE\"})",
     "legendFormat": "{{name}}_{{type}} <{{instance}}>"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (frp_server_connection_counts{type=\"udp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (frp_server_traffic_out{type=\"udp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (frp_server_connection_counts{type=\"https\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (frp_server_traffic_out{type=\"https\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (frp_server_connection_counts{type=\"sudp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (frp_server_traffic_out{type=\"sudp\", instance=\"$NODE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TunnelsActual Usage",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "frp_server_connection_counts{instance=\"$NODE\"}",
     "legendFormat": "{{name}}_{{type}}"
    }
   ]
  },
  {
   "title": "Total Traffic (Period)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(frp_server_traffic_in{instance=\"$NODE\"})",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(frp_server_traffic_out{instance=\"$NODE\"})",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Period InboundTraffic",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "frp_server_traffic_in{instance=\"$NODE\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Period OutboundTraffic",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "frp_server_traffic_out{instance=\"$NODE\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(frp_server_traffic_in{instance=\"$NODE\"}[1m])) / 60",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum by(instance) (rate(frp_server_traffic_out{instance=\"$NODE\"}[1m])) / 60 * -1",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Total Traffic (Cumulative)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(frp_server_traffic_in{instance=\"$NODE\"})",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(frp_server_traffic_out{instance=\"$NODE\"})",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Inbound Traffic (Cumulative)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frp_server_traffic_in{instance=\"$NODE\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic (Cumulative)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frp_server_traffic_out{instance=\"$NODE\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}