apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-tunnel-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: ingress-tunnel-secrets
    template:
      data:
        hcloud_token: "{{ .hcloud_token }}"
        tunnel_handshake_token: "{{ .tunnel_handshake_token }}"
        smtp_server: "{{ .smtp_server }}"
        smtp_username: "{{ .smtp_username }}"
        smtp_password: "{{ .smtp_password }}"
  refreshInterval: 15m
  data:
    - secretKey: hcloud_token
      remoteRef:
        key: "${BW_HETZNER}"
        property: tofu_api_token
    - secretKey: tunnel_handshake_token
      remoteRef:
        key: "${BW_TUNNEL}"
        property: handshake_token
    - secretKey: smtp_server
      remoteRef:
        key: "${BW_MAILGUN_ACCOUNT}"
        property: "smtp-server"
    - secretKey: smtp_username
      remoteRef:
        key: "${BW_MAILGUN_ACCOUNT}"
        property: "smtp-username"
    - secretKey: smtp_password
      remoteRef:
        key: "${BW_MAILGUN_ACCOUNT}"
        property: "smtp-password"
