apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tofu-infra-git
  namespace: networking
spec:
  interval: 30m
  url: https://github.com/mrwulf/home-cluster.git
  ref:
    branch: main
  ignore: |
    # Ignore everything by default
    /*

    # Allow walking down into the target directory structure
    !/cluster/
    /cluster/*
    !/cluster/apps/
    /cluster/apps/*
    !/cluster/apps/networking/
    /cluster/apps/networking/*
    !/cluster/apps/networking/ingress-tunnel/
