apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name ingress-tunnel
  labels:
    app.kubernetes.io/name: *name
spec:
  endpoints:
    - path: /metrics
      port: http
      basicAuth:
        username:
          name: ingress-tunnel-secrets
          key: admin_username
        password:
          name: ingress-tunnel-secrets
          key: tunnel_handshake_token
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
