apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ingress-tunnel-infra
  namespace: networking
spec:
  interval: 1h
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./cluster/apps/networking/ingress-tunnel
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: tofu-infra-git
    namespace: networking
  vars:
    - name: cloudflare_tunnel_cname
      value: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
    - name: secret_domain
      value: "${SECRET_DOMAIN}"
  varsFrom:
    - kind: Secret
      name: cloudflare-ddns
    - kind: Secret
      name: ingress-tunnel-secrets
  writeOutputsToSecret:
    name: vps-tunnel-output
  tfstate:
    forceUnlock: yes
    lockIdentifier: "8b24a051-4d98-2512-8d2f-d92b86088a49"
