---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app box
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      box:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4
            envFrom:
              - secretRef:
                  name: box-db-init-secret
        containers:
          app:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              tag: 0.26.1-hardened
            envFrom:
              - secretRef:
                  name: box-secret
              - secretRef:
                  name: box-sops-secret
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: box
        ports:
          http:
            port: 7745

    route:
      app:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: internal-gateway
            namespace: networking
        hostnames:
          - "{{ .Release.Name }}.home.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: rfc1918-ips
            backendRefs:
              - identifier: app
                port: http

    persistence:
      data:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          box:
            app:
              - path: /data/
