apiVersion: v1
kind: Secret
metadata:
    name: box-sops-secret
type: Opaque
stringData:
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:yxfE4fzxAMCGYMnXsRsM9GpEe9koJ2jpB4Q67JVUdh5ytG6l96Fexd1TfjIyZZf6gjqxmKgI5vqlFaJ6FtPaSA==,iv:Gm1TRQL/GHh+i9+fzfXevru2zqULCoOw8x4Ww5zTfSk=,tag:23orWboKrP5KkZiD39UHLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRDdZWHhMczBRNVNvalI0
            SXVKaU5ST2Q1WGFjak9VOGo5RXR1V28vakVnCm5yUTVuRlBucW0zRGtZbGtrZzRt
            QVVJdUoyMUFqb3lyQ0RoR2pURDZ3VHMKLS0tIG1MU2dzd0hvN2JaZkxVMzB1bVJm
            NE5LTlNWemdKeDM1bDZIMXVUQ20zdTAKbvfEtCEXVEMVK3kXHb2i2fBsZLibwWoz
            sUisoK7KpGCLWVsfNj5r1FR2loyP1xRds7fL2RVWAtIqQSDhtaZ1kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T19:58:47Z"
    mac: ENC[AES256_GCM,data:qo5rrRD3jg/TFsN9tGyo8RK5a+iB1S/++EY5SB+S4kZ4neVBHlzIxmIX/zoZnGWNlyxVhYbvwnln5VGJTeTneyyvvBeG/1YivnUhVqqHfdSplD69K77C/6GScKCnfOsgLMA36+dM7Q1C41NZnPsAA3F3f2x/bqQHcQq6ij8rUKY=,iv:Hplw2AcDB3nFzJ/xH1RyOV8NRjg3aHbk8Wt+AZcDJPI=,tag:lBgbw9G5xBk9Cnsq7vqsZA==,type:str]
    version: 3.13.1
