---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-control-plane-secrets
  namespace: networking
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: netbird-control-plane-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init Container Credentials
        INIT_POSTGRES_DBNAME: "netbird"
        INIT_POSTGRES_HOST: "postgres17-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # Postgres Store DSN for NetBird Management
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        NETBIRD_STORE_ENGINE_POSTGRES_DSN: "host=postgres17-rw.databases.svc.cluster.local user={{ .POSTGRES_USER }} password={{ .POSTGRES_PASS }} dbname=netbird port=5432 sslmode=disable"

        # PocketID IdP Management API Key
        NETBIRD_IDP_MGMT_EXTRA_API_TOKEN: "{{ .NB_POCKETID_MANAGEMENT_APIKEY }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Netbird DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "Netbird DB Credentials"
        property: "password"
    - secretKey: NB_POCKETID_MANAGEMENT_APIKEY
      remoteRef:
        key: "Netbird Service Credentials"
        property: "NB_POCKETID_MANAGEMENT_APIKEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
