---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oidc-client.yaml
  - ./externalsecret.yaml
  - ./management-helmrelease.yaml
  - ./signal-helmrelease.yaml
  - ./dashboard-helmrelease.yaml
  - ./route.yaml
  - ./servicemonitor.yaml
