---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-management
  namespace: networking
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    controllers:
      netbird-management:
        strategy: RollingUpdate
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              # renovate: depName=ghcr.io/home-operations/postgres-init datasource=docker
              repository: ghcr.io/home-operations/postgres-init
              tag: "18.6"
            securityContext:
              runAsUser: 65534
              runAsGroup: 65534
            envFrom:
              - secretRef:
                  name: netbird-control-plane-secrets
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
          init-config:
            image:
              # renovate: depName=netbirdio/management datasource=docker
              repository: docker.io/netbirdio/management
              tag: 0.77.1
            command: ["/bin/sh", "-c"]
            args:
              - |
                cat <<EOF > /etc/netbird/management.json
                {
                  "Datadir": "/var/lib/netbird",
                  "HttpConfig": {
                    "Address": "0.0.0.0:8080",
                    "AuthAudience": "$NETBIRD_AUTH_OIDC_CLIENT_ID",
                    "AuthClientID": "$NETBIRD_AUTH_OIDC_CLIENT_ID",
                    "AuthIssuer": "https://id.${SECRET_DOMAIN}",
                    "AuthUserIDClaim": "sub",
                    "OIDCConfigEndpoint": "https://id.${SECRET_DOMAIN}/.well-known/openid-configuration",
                    "IdpSignKeyRefreshEnabled": true
                  },
                  "PKCEAuthorizationFlow": {
                    "ProviderConfig": {
                      "Audience": "$NETBIRD_AUTH_OIDC_CLIENT_ID",
                      "ClientID": "$NETBIRD_AUTH_OIDC_CLIENT_ID",
                      "Issuer": "https://id.${SECRET_DOMAIN}",
                      "Scope": "openid profile email groups",
                      "RedirectURLs": [
                        "http://localhost:53000",
                        "https://nb.${SECRET_DOMAIN}/auth",
                        "https://nb.${SECRET_DOMAIN}/silent-auth"
                      ],
                      "UseIDToken": true
                    }
                  },
                  "DeviceAuthorizationFlow": {
                    "Provider": "none"
                  },
                  "IdpManagerConfig": {
                    "ManagerType": "pocketid",
                    "ClientConfig": {
                      "ClientID": "netbird",
                      "ClientSecret": ""
                    },
                    "ExtraConfig": {
                      "ManagementEndpoint": "https://id.${SECRET_DOMAIN}",
                      "ApiToken": "$NETBIRD_IDP_MGMT_EXTRA_API_TOKEN"
                    }
                  },
                  "StoreConfig": {
                    "Engine": "postgres"
                  },
                  "Signal": {
                    "Proto": "https",
                    "URI": "nb.${SECRET_DOMAIN}:443"
                  },
                  "Stuns": [
                    {
                      "Proto": "udp",
                      "URI": "stun:vps-backup.${SECRET_DOMAIN}:3478"
                    },
                    {
                      "Proto": "udp",
                      "URI": "stun:stun.netbird.io:5555"
                    }
                  ],
                  "Relay": {
                    "Addresses": [
                      "rel://vps-backup.${SECRET_DOMAIN}:33073"
                    ],
                    "CredentialsTTL": "24h",
                    "Secret": "$NETBIRD_RELAY_AUTH_SECRET"
                  },
                  "TURNConfig": {
                    "Turns": [],
                    "Secret": ""
                  },
                  "ReverseProxy": {
                    "TrustedHTTPProxies": [],
                    "TrustedHTTPProxiesCount": 0,
                    "TrustedPeers": [
                      "0.0.0.0/0"
                    ]
                  }
                }
                EOF
            envFrom:
              - secretRef:
                  name: netbird-control-plane-secrets
              - secretRef:
                  name: netbird-oidc-credentials
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        containers:
          app:
            image:
              # renovate: depName=netbirdio/management datasource=docker
              repository: docker.io/netbirdio/management
              tag: 0.77.1
            command: ["/go/bin/netbird-mgmt"]
            args:
              [
                "management",
                "run",
                "--config",
                "/etc/netbird/management.json",
                "--port",
                "8080",
                "--log-file",
                "console",
                "--disable-anonymous-metrics",
              ]
            env:
              NETBIRD_USE_AUTH0: "false"
              NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT: "https://id.${SECRET_DOMAIN}/.well-known/openid-configuration"
              NETBIRD_AUTH_AUDIENCE:
                valueFrom:
                  secretKeyRef:
                    name: netbird-oidc-credentials
                    key: NETBIRD_AUTH_OIDC_CLIENT_ID
              NETBIRD_AUTH_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: netbird-oidc-credentials
                    key: NETBIRD_AUTH_OIDC_CLIENT_ID
              NETBIRD_AUTH_SUPPORTED_SCOPES: "openid profile email groups"
              NETBIRD_AUTH_REDIRECT_URI: "/auth"
              NETBIRD_AUTH_SILENT_REDIRECT_URI: "/silent-auth"
              NETBIRD_TOKEN_SOURCE: "idToken"
              NETBIRD_AUTH_DEVICE_AUTH_PROVIDER: "none"
              NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: netbird-oidc-credentials
                    key: NETBIRD_AUTH_OIDC_CLIENT_ID
              NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE:
                valueFrom:
                  secretKeyRef:
                    name: netbird-oidc-credentials
                    key: NETBIRD_AUTH_OIDC_CLIENT_ID
              NETBIRD_AUTH_DEVICE_AUTH_SCOPE: "openid profile email groups"
              NETBIRD_AUTH_DEVICE_AUTH_USE_ID_TOKEN: "true"
              NETBIRD_MGMT_IDP: "pocketid"
              NETBIRD_IDP_MGMT_CLIENT_ID: "netbird"
              NETBIRD_IDP_MGMT_EXTRA_MANAGEMENT_ENDPOINT: "https://id.${SECRET_DOMAIN}"
              NETBIRD_STORE_CONFIG_ENGINE: postgres
              NETBIRD_NETWORK_NET: "100.110.0.0/16"
              NETBIRD_MGMT_API_PORT: "8080"
              NETBIRD_MGMT_METRICS_PORT: "9090"
            envFrom:
              - secretRef:
                  name: netbird-control-plane-secrets
              - secretRef:
                  name: netbird-oidc-credentials
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 15
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
    service:
      app:
        controller: netbird-management
        ports:
          http:
            port: 8080
            appProtocol: kubernetes.io/h2c
          metrics:
            port: 9090
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /etc/netbird
      data:
        type: emptyDir
        globalMounts:
          - path: /var/lib/netbird
