---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netbird-management
  namespace: networking
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: netbird-management
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netbird-signal
  namespace: networking
spec:
  endpoints:
    - port: grpc
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: netbird-signal
