---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: development
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 1
    cache:
      enabled: true
      dir: /data/cache
    container:
      require_docker: false
