---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: forgejo-runner-secret
    template:
      data:
        token: "{{ .TOKEN }}"
  data:
    - secretKey: TOKEN
      remoteRef:
        key: "${BW_FORGEJO_CREDENTIALS}"
        property: "token"
