# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./cluster/apps/vpn/qbittorrent/app/
  components:
    - ../../../../templates/volsync/primary
  dependsOn:
    - name: rook-ceph-cluster
    - name: pod-gateway
    - name: qbittorrent-incomplete-pvc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vpn
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: *app
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_NFS_START_MINUTE: "41"
      VOLSYNC_B2_START_MINUTE: "06"

  retryInterval: 2m
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-incomplete-pvc
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./cluster/templates/volsync/local-only
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vpn
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: qbittorrent-incomplete
      VOLSYNC_CAPACITY: 600Gi
      VOLSYNC_NFS_START_MINUTE: "05"
      VOLSYNC_B2_START_MINUTE: "35"
      VOLSYNC_CACHE_CAPACITY: "60Gi"
      APP_UID: "985"
      APP_GID: "977"
      VOLSYNC_MOVER_MEMORY_REQUEST: 2Gi
      VOLSYNC_MOVER_MEMORY_LIMIT: 4Gi
  retryInterval: 2m
