---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: ingress-vps-us
  namespace: networking
spec:
  jobName: ingress-vps-us
  targetEndpoints:
    - targets:
        - "${VPS_US_PUBLIC_IP}:8082"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: traefik
    - targets:
        - "${VPS_US_PUBLIC_IP}:9091"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: netbird-relay
    - targets:
        - "${VPS_US_PUBLIC_IP}:9100"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: node-exporter
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: ingress-vps-eu
  namespace: networking
spec:
  jobName: ingress-vps-eu
  targetEndpoints:
    - targets:
        - "${VPS_EU_PUBLIC_IP}:8082"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: traefik
    - targets:
        - "${VPS_EU_PUBLIC_IP}:9091"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: netbird-relay
    - targets:
        - "${VPS_EU_PUBLIC_IP}:9100"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: ingress-vps
        - targetLabel: service
          replacement: node-exporter
