---
ingress:
  - hostname: "*.${SECRET_DOMAIN}"
    originRequest:
      http2Origin: true
      keepAliveTimeout: 3600s
      originServerName: "external.${SECRET_DOMAIN}"
      tcpKeepAlive: 7200s
    service: https://traefik-external.networking.svc.cluster.local:443
  - service: http_status:404
