---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: wallos
spec:
  name: Wallos
  launchUrl: https://${GATUS_SUBDOMAIN}.home.${SECRET_DOMAIN}
  callbackUrls:
    - https://${GATUS_SUBDOMAIN}.home.${SECRET_DOMAIN}
  allowedUserGroups:
    - name: users
      namespace: auth
  secret:
    name: wallos-oidc-credentials
    keys:
      clientID: OIDC_CLIENT_ID
      clientSecret: OIDC_CLIENT_SECRET
      authorization_url: OIDC_AUTH_URL
      issuer_url: OIDC_ISSUER_URL
      token_url: OIDC_TOKEN_URL
      userinfo_url: OIDC_USERINFO_URL
