---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: towonel-edge-na
  namespace: networking
spec:
  jobName: towonel-edge-na
  targetEndpoints:
    - targets:
        - "${VPS_PRIMARY_PUBLIC_IP}:9090"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: towonel-edge-eu
  namespace: networking
spec:
  jobName: towonel-edge-eu
  targetEndpoints:
    - targets:
        - "${VPS_BACKUP_PUBLIC_IP}:9090"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: towonel-hub
  namespace: networking
spec:
  jobName: towonel-hub
  targetEndpoints:
    - targets:
        - "towonel-hub.networking.svc.cluster.local:9091"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: towonel-agent
  namespace: networking
spec:
  jobName: towonel-agent
  targetEndpoints:
    - targets:
        - "towonel-agent.networking.svc.cluster.local:9090"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
