apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
stringData:
    DATA_SOURCE_NAME: ENC[AES256_GCM,data:blDW/Bzlz8RF/fgEDnGxnkxym2t3Cr/tjqlWzpgyJsc9wH0VUtC4OuPPJACzcNfXlU3o6IwcX5f6ioMjrWFV6OsRQ8iv,iv:u/E6+lPFVXLYLRRpCRxyvdIqaQ7qjCQjcC1tW5dB+Gs=,tag:FQkp8CnUPI6Tq0nYiDprlw==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:aBoLvTU+fyhg,iv:UTSFAgkWLVSOEfXQCSuvY60tsrEGGSTFFtr+2MZKTjs=,tag:owB6hb7i5zfHg58r8oMtQg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:d/CPNWuiGyOqLZxLif/SIyzFskBPCOSRAXIIBWgRGPw=,iv:EpsXsQNY8P0V3PH+uSPehOxX1z2MvhdG1Rm/t2VJX3E=,tag:vemufIqRKiS8gYF1/juOrA==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:30zsBvSSqY8W/NKcP4S8Ug57R2ONudu20YmxUGkQc1c=,iv:v4otB9Xm1BW6nsa3xf4vOZP82C8ad1G+ZgB37CnWirE=,tag:usQfrkuKHPg3xXhbNGuE0g==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:3h6kXLckGEGG,iv:Xr7QKJyDe3LVlTgUprL44pl0bF4xMmNHcmcjK7yZgIA=,tag:SV/3fjUL+EnTvguUxWn7uQ==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:HcSsDOLTqn/d,iv:uruYPUCNOTrpg141Af+Pupfh8/m9bkUBCsIO5pCjPZc=,tag:e1nsXpQ6H7pJrVbWKFhzcg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:FGfopwmsfUP8dxEpGzvhcV2hKbpDYJmPdcSfcsu7r6o=,iv:xT5aiMmX+TRyYlc6Ac0Z3iaqtCOT+6I4O4ViTN0elwY=,tag:9yD40bbGyCeQyKoNxkzkGA==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:o/sBVNvVENbP,iv:SBFKNgBvPoZGYHGutXPZwPoum2PozQm1Mzeu/P/iZjY=,tag:f1OMBK/LDjXKmzclsRohrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM2J4UzZ1bkFEVjk0M1Bh
            dUp2UmEzWHllWExIZnBEQTA1RGNIbndUMkNZCnhIc2ZENGJydisvUDBUTXJMeHJD
            dmJKemwrbHhRbnhWaGgxQWhwYTR6WFEKLS0tIElwa0VJYTBzUjhkOUkyT0N0RkM5
            VVpyeU4xK1F5OXhhWDJULzlMb09zZ0EKqYGcKaoNhamWq4ShcAPvmyknsjuhbJkJ
            1DRF2JWocuhhnQVSn4rUdNdXxbUBSM6aS3CUWA1dmdwyGU8D+j9CrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T22:24:34Z"
    mac: ENC[AES256_GCM,data:jZVe3YMNgVjHEQKyWSGsDENYqf5KWgizwsdaCawqTB88DBOJCTomJQf8Y79OUhwFUP8NoNZucmJBmEeFLHxecEWZESFp8lAm3xFZDi/DujnJvXCH0febAmN5ONLCQAE4wvyVHoHS9yBw4OP587TTFB8He23qe3RZPxpNioPTE3M=,iv:N+ySN0gt15mjPorwWDXbgVXg7K1blgA7CKCkWo3u84g=,tag:3VKVVt79iVssSCN4iJmkIA==,type:str]
    version: 3.13.1
