---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: local-path-provisioner
  install:
    disableHooks: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    disableHooks: true
    remediation:
      retries: 3
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/mnt/extra/local
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    helperPod:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
