---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: k8s-admin
spec:
  users:
    userRefs:
      - name: brandon
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: household-users
spec:
  users:
    userRefs:
      - name: brandon
      - name: chelsea
      - name: emerald
