---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: admin
spec:
  users:
    userRefs:
      - name: brandon
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: users
spec:
  users:
    userRefs:
      - name: brandon
      - name: chelsea
      - name: emerald
