---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    operator:
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
      dashboard:
        enabled: true
        grafanaDashboard:
          enabled: true
          instanceSelector:
            matchLabels:
              dashboards: grafana
    instance:
      enabled: true
      name: pocket-id
      serviceMonitor:
        enabled: true
      spec:
        ui:
          appName: "Home PocketID"
        # renovate: depName=pocket-id/pocket-id datasource=github-releases
        image: ghcr.io/pocket-id/pocket-id:v2.8.0
        encryptionKey:
          valueFrom:
            secretKeyRef:
              name: pocket-id-secret
              key: ENCRYPTION_KEY
        databaseUrl:
          valueFrom:
            secretKeyRef:
              name: pocket-id-secret
              key: DATABASE_URL
        fileBackend: database
        appUrl: "https://id.${SECRET_DOMAIN}"
        geoip:
          maxmindLicenseKey:
            valueFrom:
              secretKeyRef:
                name: pocket-id-secret
                key: MAXMIND_LICENSE_KEY
        emailNotifications:
          verification: true
          oneTimeAccessAsAdmin: true
          oneTimeAccessAsUnauthenticated: true
        smtp:
          host: smtp-relay.system.svc.cluster.local
          port: 2525
          from: pocket-id@${SECRET_DOMAIN}
          tls: none
        persistence:
          enabled: false
        metrics:
          enabled: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        versionCheckDisabled: true
        analyticsDisabled: true
        podTemplate:
          spec:
            initContainers:
              - name: init-db
                image: ghcr.io/home-operations/postgres-init:18.4
                env:
                  - name: INIT_POSTGRES_HOST
                    value: postgres16-rw.databases.svc.cluster.local.
                  - name: INIT_POSTGRES_DBNAME
                    value: pocketid
                  - name: INIT_POSTGRES_SUPER_PASS
                    valueFrom:
                      secretKeyRef:
                        name: postgres-superuser
                        key: password
                  - name: INIT_POSTGRES_SUPER_USER
                    valueFrom:
                      secretKeyRef:
                        name: postgres-superuser
                        key: username
                  - name: INIT_POSTGRES_USER
                    value: pocketid
                  - name: INIT_POSTGRES_PASS
                    valueFrom:
                      secretKeyRef:
                        name: pocket-id-secret
                        key: DB_PASS
