apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:yT0zcEWrK4JtdN2dE674MO8db9y14TyknDgCf2vzAuM=,iv:MNlTUZpBEULF6Zm+XACIYf2uRjMdQ2xYQ1SssA9eSGc=,tag:62g+yELmF3FtmlU6Xo9fTQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:n+hgqFSuOSQ+5TfvhwAvVmXnjlpLvd/y5BUpEu5mzUk=,iv:UgWZQ1RId3q9VC1WGLNAULIOvap+Dm9Pq/McjrgLC+0=,tag:w1HpFNJsdx/Lepg6zzQHww==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0k1r81+D6p8maYxdp8Ogj27IE1zfEAU9erp6A8xH+pYzQy99AE40HGFN5r8VAOvQPy5ks9VRwxjDkggvg75yQV1XrYbmiGXjfTKsBkvGUMhL87ACeyiZTU5foJywXrZzBEKc9+rvqIPYgAuw,iv:HiU0fzxChX7tc2kzOakei2ceoTOz+m4ho90hnYwA0Gc=,tag:idx3/bacKTk121tlGZyJUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTG52Rm9xSWR6NlRadGc4
            dnprODl2MU96YVZtbzIwaTF3elo4eFUxWlhVCjgwUFpONzJSNnRaQ21henZwZVJI
            MDVqVDkxMDVvTGlPMUpzb0puZURpTHMKLS0tIFZPc0pGL3V5V0IwRFdvU3BMOXFF
            K2RsaW0xcTQ4bW1lbGZNOCtMM21yVDgKU/fMCPSPewt34VmTUnFSyShlnUw+qWB0
            eGUJuHC4w6sO/ZD+I75UIkuUbsBFS+ZGzet+9h8JwnxrkbHyQK/bxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T08:58:54Z"
    mac: ENC[AES256_GCM,data:xNqTwCni89faTVcpcbZtHt2j4Ei05LPgAZLpmZCQv/UFvv6rHUsIGh4FbLdNcWPox/7LZytVZXlJDV5kUbT1im5aOBBW3APGPv22HJpeDjdJ8k7PTQ64VNzQ7CWrWAlY2LxGB52SJ6CzbQF6CHfH/UIlAI0I1pyo8GfrG4ffcIA=,iv:21KBMugX2yUfIGKWuFLSpMOKQxYE02fZQqbWPbj8vDw=,tag:SxmFPUWUfv6hyN+lKDK0mg==,type:str]
    version: 3.13.1
