apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:OZ0DmplsEBYt+brQJrL7O982obsMwfPCmSW8ofpN1ksvPMmnpRsFvJAtDJ5JCufvmPfUpQUUaPq3aTVHX0snTuDNAtrkSMfIVuFjoNFb/ohzCoOQpwPaMVGkBYZXuAwFGtQJQfwUlT6HaaJU,iv:o8S5YAazOeYq4BIVg5h9/2huHDpn7pUJaAhjCTslQH4=,tag:a5NH3ZVRXNmf7hYm5NRLSw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:UlrURlew+xc8hoXgWmpyR2w3tisZWstQeXy9bLRLiyM=,iv:4faS4u1nZymjBABPWpdinkI6LmyvuJ0fTKyeSmFWaD0=,tag:mWN92Z20myqAKalTjoIWpg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:7QgJKm8wCV35ClJH7wJmLyF+u9jpSpqMGM/DJ6kdqrY=,iv:P3XNO2iSF43G+SX+I7pX3LJ0FuJfVB3rB4Bc3y2avro=,tag:Rt3me+xN9h2Vsao7pn+Dug==,type:str]
    MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:VQrqKhT6agr+mYJ+HON6Z4JFXpW7i0I/DL4rK0+az/DdoFhdc982+Q==,iv:8GXLlmH68Q/oegNEF3dVDCZs7YEeo/Mibk1hgwPwno0=,tag:wqXD5XNsgW7WNAzrM5ICQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN2hNTnh2ZzMrdi9BQXlF
            VWp3OWdyN2lNbnRkcjNoNWcreFdQTkNrVFJRCkQ0K0pWK3FsTWVFd1hkSTFCcXQv
            T0d6bW9tZ2Q5NmhUaHVpczE1K053aE0KLS0tIGp1bUNMZFZyUFVnaGZObENUQ014
            b0JocXlEVVVTdUVDcVB3UjNPZmRva1UKCR8mGva4aHuScEbfVRMGZy+hQQpv7T2N
            DLmXYu8wKz1R2req0A/SMc6RETrqDnTryW+5vlLMXWkryGxAqe4KFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T23:04:17Z"
    mac: ENC[AES256_GCM,data:2w+WB+yHuYbEolLEXWa8P6zlpN2uqJu7ZFi+wIfGtPBLYGRysRo0Xox40ujmd9qaLdFlTUTcvNfXgAFgqJ8qn6Cyqo2sdI8NQ3eldWV/EQhB1XlY1QpEWhcTD9nrgQ6TPb8OGIwIkHz5e0aOIxNUoUCNT89uP9xzcDxyGnjvvjk=,iv:eVRKuuX7p8Z27sUzEspfTAkcydLUTrFx9rhJesytzPY=,tag:R9TK+Za3LHe1elIdsAXCDg==,type:str]
    version: 3.13.1
