---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pocket-id
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
  selector:
    matchLabels:
      managed-by: pocket-id-operator
