---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: affine-secret
    template:
      data:
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.databases.svc.cluster.local:5432/affine"
        AFFINE_PRIVATE_KEY: "{{ .AFFINE_PRIVATE_KEY }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: affine
        INIT_POSTGRES_HOST: postgres17-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "AFFiNE DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "AFFiNE DB Credentials"
        property: "password"
    - secretKey: AFFINE_PRIVATE_KEY
      remoteRef:
        key: "AFFiNE Private Key"
        property: "password"
