---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oidc-client.yaml
  - externalsecret.yaml
  - fix-private-key-configmap.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
