---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - route.yaml
  - secret.sops.yaml
  - ./datasources/datasource-prometheus.yaml
  - ./datasources/datasource-alertmanager.yaml
  - ./datasources/datasource-loki.yaml
  - ./folders/folders.yaml
  - ./dashboards/dashboards-apps.yaml
  - ./dashboards/dashboards-ceph.yaml
  - ./dashboards/dashboards-cilium.yaml
  - ./dashboards/dashboards-flux.yaml
  - ./dashboards/dashboards-kubernetes.yaml
  - ./dashboards/dashboards-unifi.yaml
  - ./dashboards/dashboard-home.yaml
