---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-node
  namespace: networking
spec:
  interval: 1h
  url: oci://codeberg.org/towonel/charts/towonel-node
  ref:
    tag: 1.5.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-hub
  namespace: networking
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: towonel-node
    namespace: networking
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: towonel-hub
    hub:
      enabled: true
    edge:
      enabled: false
    controllers:
      main:
        initContainers:
          init-db:
            image:
              # renovate: depName=ghcr.io/home-operations/postgres-init datasource=docker
              repository: ghcr.io/home-operations/postgres-init
              tag: "18.6"
            securityContext:
              runAsUser: 65534
              runAsGroup: 65534
            envFrom:
              - secretRef:
                  name: towonel-hub-secrets
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
        containers:
          main:
            envFrom:
              - secretRef:
                  name: towonel-hub-secrets
              - secretRef:
                  name: towonel-hub-oidc-credentials
    serviceMonitor:
      main:
        enabled: true
    route:
      main:
        enabled: true
        parentRefs:
          - name: external-gateway
            namespace: networking
            sectionName: https
        hostnames:
          - "towonel-hub.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: traefik-middleware-chain-no-auth
            backendRefs:
              - port: 8443
