apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-secret
type: Opaque
stringData:
    NTFY_ACCESS_TOKEN: ENC[AES256_GCM,data:rUxgxZo4a1nvned703aNg4YEUumpe+u0z14n2B2MkOU=,iv:hdlWeZ2yNDOu5NxF25SRf+Sm3HOiLVTwznJ+Vmd+C+o=,tag:5Jo692fnhDmXQEdJkIJLeQ==,type:str]
    WEBHOOK_PASSWORD: ENC[AES256_GCM,data:JZMVXhQI6k4P5MeoaZbQsA2kmgOlik9J7eEYN582,iv:lfimdFBKIKMzphRR0Kk7nc4jqraRYrDM7ILlHRUPXuA=,tag:R4J3U1pQNEonPxgmuykaWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjRTWVJJU2JrRFU5ZVdF
            ME1GOXgvVmRrQTVTWmNvUTlJSFNuMlJSSERNCmZBVW1QWW5hVnFtQ2JqMkUzSi9V
            OGJ5bjB6NGVkNlhaczdCOGhzQnI5TTAKLS0tIHJZbHl1bTA5QllSUUhRVis0QWJM
            bU8yTWdrcFM0dEhYTm5KN2xZVlZqbWcKER+byU1A6eNTT+fYXBk9TlFswyGHMO03
            Y/LzklZ6hC8Zzh0TY2kuMYQT8JztMR4PLHXAEG6h0eds9EXBMjXScA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T06:32:49Z"
    mac: ENC[AES256_GCM,data:7J4aOx0Qw87r/IGYCVKH+GBZnhZoqBO7nkKUHFAglIYDeCp9NKn7UfIl+w8dGx0G9Pn9McxZw49iv2siz21bulOdXT8qHNKf2XgilsJMF2E3JdT10XCYu/EcJC4I0zECswdw5VCuBNHbqw6yHtAp5QeV3X+Th9Tq37asQE9R4Fs=,iv:SQafmQ83p0WxfZiS+DGonm61/IOJq/wngRelQ6ZOXLY=,tag:2hyca5XOYeSPGXSujBPZtw==,type:str]
    version: 3.13.3
