apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-secret
type: Opaque
stringData:
    NTFY_ACCESS_TOKEN: ENC[AES256_GCM,data:BcfBCx0IVsqtNoTpvVFDypoL1UYZFeDJ08iI6JPtnrQ=,iv:PAOlMgeT9g1bEZSI12LYKsTokhTvSPPMQjH5Zhxu43Q=,tag:d9tG4laASetljKkmTXnhow==,type:str]
    WEBHOOK_PASSWORD: ENC[AES256_GCM,data:PVrIMeVnzF8RtXL2VakjabK38Ta8WSOUY9s7UAW/13Y=,iv:pWKp+F8wUp4mkfAkkq1BTTpQWrrfzUCxlCacLjmQni8=,tag:lxrG5RGEHs72BePJ3GtQsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZkN3VnVFRkVrZklzeDlO
            U05CQnQzVHQxSDBQZE9jQi90K2psTWJVaUFRCmU5Y2N1M1U1NWF1ZEhuamlIUitS
            R0lhamxQMm1IQjRhelNTTmljbDVaSXMKLS0tIDNRWitUc2VSc0hhTjdpSmZDckJC
            V1pkVmZGVVlXZURFeVFRSUZrR1NHMncK6zTfJo/bdyyCRqDBZiQxnwHpNnAtBllL
            PwHXvrXq55uWokTn3CHo4Vwae26q1F4D1j+MQlXZ+xTsean/Bc6iJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T06:26:10Z"
    mac: ENC[AES256_GCM,data:Z5b5ahofl47asWOyEpB1NSmoz4Z5IBSr7ji2HTp2uD/CkfZ0s28gPcT6i4vTzrFauUzO88Id2cyDcesBo/IJVyuvC9FTR0DnFvjuehDtLHqibeQpq2+jF51VX1gVse+X9lR5tfZ0K/jYdnbuOeOU1x83ndNr3+Mqf98UEYGxWNo=,iv:t8OiPN/D3ei48dtN3oTaHMHqbReQeLkuAhzktqnW6gg=,tag:ZdTmTtqxGizsbKB/HZuT5A==,type:str]
    version: 3.13.3
