apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  rotate-server-certificates: true
  max-pods: 150
config:
  imageGCLowThresholdPercent: 60
  imageGCHighThresholdPercent: 70
  maxParallelImagePulls: 10
  serializeImagePulls: false
  shutdownGracePeriod: 60s
  shutdownGracePeriodCriticalPods: 30s
