apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.0.0.1
  - address: 10.0.1.1
searchDomains:
  disableDefault: true
hostDNS:
  enabled: true
  # Incompatible with Cilium bpf masquerade. https://github.com/siderolabs/talos/issues/8836
  forwardKubeDNSToHost: false
  resolveMemberNames: true
