---
apiVersion: v1
kind: ConfigMap
metadata:
  name: super-productivity
data:
  Caddyfile: |-
    {
      admin off
      auto_https off
    }
    :8080 {
        log {
            output stdout
        }
        @api {
            path /api*
        }
        handle @api {
            uri strip_prefix /api
            reverse_proxy localhost:1900
        }
        handle {
            reverse_proxy localhost:80
        }
    }
