---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: super-productivity-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: super-productivity-db
    template:
      data:
        INIT_POSTGRES_DBNAME: &dbName "super-productivity"
        INIT_POSTGRES_HOST: &dbHost "postgres16-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres16-rw.databases.svc.cluster.local:5432/super-productivity"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "${BW_POSTGRES_SUPERUSER}"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "${BW_SP_DB_CREDENTIALS}"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "${BW_SP_DB_CREDENTIALS}"
        property: "password"
