apiVersion: v1
kind: Secret
metadata:
    name: super-productivity
type: Opaque
stringData:
    SP_JWT_SECRET: ENC[AES256_GCM,data:0vteE3OsXXsXXgwACoFPoB7icxsyD0ZNKs17gdpdGgx4P6gDZQOcSsQ3tEEq4O4W95MfKGBu+4AYGe6RtgUS9Q==,iv:zbXLwYSXJ+ocKiPxJyuBqb1l5vdrue3sh9kmKtjTSYI=,tag:2YrQcxzTI1OMMJ0otw8qDA==,type:str]
sops:
    age:
        - recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbFhaWE1mVVBkR3M1VjRL
            OGlEU0F2UlFJNWwwMkE1eUoyQjc5MU1pbVgwCjBhcHNkSU5XeUZ6cnFDNHd6Rnp3
            YzNqVlhBczJSNlh6NXNmVFp0ZzZ0cXcKLS0tIFBHdjJUS2k5MHJnMjBoaUt4U1VG
            cC9LNDFzQ2NtL3pnOUtpc1pBMVVjbXcKdBPXDdNnEHVq5+xkGInJ4vclA2dlpZqu
            IW5K4XYgSYmVGzb4KJ4PELZIxSEC5+PoxaQ2T5LuaqCV4HT2WdCUzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T17:07:10Z"
    mac: ENC[AES256_GCM,data:7GtNruwPzU3tEAo7AGaw6g51gi3Mx83iDMj71msetUIlgeQPmiI5vakk7LghC63HIYWHPD/QNx0wvFjjRJFYV7f9dby46z92CGA63cIDTRtnRhAzn0e8FdAWeXNbIoH3ph7hGrXIdRlhRJTRGH3jXvbSLM7CxOSXMsD3/Qe9lNQ=,iv:Cr31DLzWtBzvzgaX4hFGYjK26YPEgdiDmncdif5Y4lI=,tag:qCYwRmRaYmFfKMIYvopnbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
