---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oauth2-proxy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      oauth2-proxy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/oauth2-proxy/oauth2-proxy
              tag: v7.6.0
            env:
              - name: OAUTH2_PROXY_PROVIDER
                value: oidc
              - name: OAUTH2_PROXY_UPSTREAM
                value: static://202
              - name: OAUTH2_PROXY_HTTP_ADDRESS
                value: 0.0.0.0:4180
              - name: OAUTH2_PROXY_REDIRECT_URL
                value: https://oauth.${SECRET_DOMAIN}/oauth2/callback
              - name: OAUTH2_PROXY_COOKIE_DOMAINS
                value: ".${SECRET_DOMAIN}"
              - name: OAUTH2_PROXY_WHITELIST_DOMAINS
                value: "*.${SECRET_DOMAIN}"
              - name: OAUTH2_PROXY_COOKIE_SECURE
                value: "true"
              - name: OAUTH2_PROXY_EMAIL_DOMAINS
                value: "*"
              - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
                value: "true"
              - name: OAUTH2_PROXY_REVERSE_PROXY
                value: "true"
            envFrom:
              - secretRef:
                  name: oauth2-proxy-secret
              - secretRef:
                  name: oauth2-proxy-oidc-credentials
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 64Mi

    service:
      app:
        controller: oauth2-proxy
        ports:
          http:
            port: 4180

    route:
      app:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: external-gateway
            namespace: networking
        hostnames:
          - "oauth.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: traefik-middleware-chain-no-auth
            backendRefs:
              - identifier: app
                port: http
