apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:bD3TbEf+hMxGfloPPq2O/8+6UoemMNdTA0MrcGbS2LQ2BCOKgQleUKv77Is=,iv:0Vr7qrSFhKkgXDUrcG53MYrfMbKIi0wWa9/ZpqTHqHY=,tag:3YVxzdc5J0Ahltf9gtlmFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTFBmKzBubGlKWnFadUIx
            RFlLVUJZaVl5azdCOUY2akllT3JSZHBqMmtjCi83ZHdTQUJlRFlJVWIrQ1Q4L2R1
            TWF5RDZaK1pkeXRvOWtSeEM4dlJ2dTAKLS0tICtKenp0UitxSnlYTGZoL0hzOEt1
            REJoNWdKWDZ1aW9pd0xmVTAyckZEb3MKR+viRbI1tIgtcoaG25sAQoAHgoLedjeS
            L+eV+iZ3Yog+SPFVd9nXDvcgmR6E4zUxVdD1ZlTFTyHdvIzWLxJBcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T23:09:03Z"
    mac: ENC[AES256_GCM,data:hFfSujbxyq4yPsUPRI/vvRz/YoRvVvp+zR+EhZBCW4r1vXXi20kWsZWy7LRXzBbQrW+tBwtuhzx0WkPsPXOcoaxYPKhrn4QUp7bfRYvNhFB7CsK29FKbJVUS4eTr4HDJbG7EEAiPTEafxz95Xqm73rrbdrtMF0SvYhn6xRAQlRo=,iv:4S7otoA1cd9j8WE6U/R6E8sIUIjHfYs7NkotQRTrCag=,tag:A1deGvZxNWOaE3KXKcKZDA==,type:str]
    version: 3.13.1
