apiVersion: v1
kind: Secret
metadata:
    name: netbird
stringData:
    SETUP_KEY: ENC[AES256_GCM,data:ezemC9H02+8OKvJ9U99+jijoUkTlQUdtRkNaAZFmG37HeQY3,iv:fuWwbhDYiuKm0MXaPMz6WQrDQl4LzNjHGPOTOveddOc=,tag:geQw9A8HNpHzPMqhSiEtXg==,type:str]
    OPNSENSE_SETUP_KEY: ENC[AES256_GCM,data:IiG4gUF+h6kdkKk8w2YVtDCaCWD77DolzS6fmZ7N5ikzemz7,iv:8hk/xQBnfYLqIEnOJ38gzBMN7e9eE/7Q15/r0ipB8lk=,tag:sY6TuhG160pkSAM6R8LeRg==,type:str]
    MANAGEMENT_URL: ENC[AES256_GCM,data:A/02woQAFxPe2K56or9GVO3xX7q5TQ==,iv:ImTH0M8DvY6D3jy3Sbxm5bahypkDsF7JaBOsXH/6gAc=,tag:HYEApo0isbsAg9TOOqsLVw==,type:str]
    NB_API_KEY: ENC[AES256_GCM,data:9bCU7PvSzDJmDErl45EOI1dGrjmQGwHGE6FDqv8fCE3AtClkIICAYA==,iv:jOX+3MSlHs0fMZCaUkETUW9rAj79Qnd+fp67fVGv40s=,tag:4o48I2OFwlHW/mfEmltcVA==,type:str]
    NB_CLOUD_API_KEY: ENC[AES256_GCM,data:TirIpKnZmKaJnsjAKTpM0er2sVaQCy2UaOmOGsPsPbapM340eEU5yQ==,iv:YKrL4bDtikbmFVAIv3SkUfMsPtRv42LtrpYzfyJm6Rs=,tag:kXOFQsCCuyviHGewhLmOSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVVZLWGJJMEV2blpCcFVB
            YlNBZGJTUnBseDFXSDNxUG9QQWUvTmJrbnpRCndVMTJvSDNnTkZyMDV6SW5nSUZK
            MDl6VlJLeHloK3JjeUN3Z21wTWpEb00KLS0tIHMyTE8xL2tuMWdJa29VZHVwbEJL
            OWZnOWhUQ0pFWmFHcldaNXVvMk5xWU0KcWsXTg+IeGXAhxiXBTZveJFCIZ97zt2U
            bPhKucPTvc/4KxacJOrCr75p1KH2wbRdt1Gt6IfpqgAnUBzMTR+djg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T20:17:49Z"
    mac: ENC[AES256_GCM,data:ztpu0FWcts4r95KYaQmIhH+eOAwfjTHN4nng0XacUtyuTQzUCFNdHKbF6R17fmsFCqgT6CFnyByH4suu7nCzPrCE5FjlUZz8D6VIFZjrNcgXR998kiwhjoT6nKaIVMWZTiKoiEEWzrSYgjnF9UPYJ9SV1UEgC5F2H37FlDQXUhM=,iv:EvFkuoqcaXTsulhvVPnOsDR1X+MtXQZFvrL+I3w3jrw=,tag:JoHrBYooHL5v43TENvGOww==,type:str]
    version: 3.13.2
