apiVersion: v1
kind: Secret
metadata:
  name: netbird
stringData:
  SETUP_KEY: ENC[AES256_GCM,data:MBNTTxtlC8/XJO3kaNEfWlMnNXfMIrWnbmyh1RuSV0EaNbGN,iv:ucUFsSODRNjMLRn8k/kSSJiHng+uPFJ6/1KCGuVlI+8=,tag:YarxXgBKAZF0zqGKGGR3EA==,type:str]
  OPNSENSE_SETUP_KEY: ENC[AES256_GCM,data:J3Z82kkQp0vCg/X00mskrtUUXxrBkHnjDIuWXiwouhg/sK/u,iv:dMyZf/EuTkDZHhQYFQi9+io5TGXFcd66G9wM+gBTg7Q=,tag:gDts2JKCbFiRZMDmUAdUVA==,type:str]
  MANAGEMENT_URL: ENC[AES256_GCM,data:pLt8oDVOoM6SlwN5VUKI54YarCavZw==,iv:O73ppFZfk6R94sDkJhxa3T2UCVAQr1QpsFlZphw7G5A=,tag:hDGwQkvvJoLUtwWWSxoAGA==,type:str]
  NB_API_KEY: ENC[AES256_GCM,data:1miOXlBcgSRQBNs7xDmXYicjAgKc2sFREpkEUdBTvJ2NsaayFUlYMQ==,iv:AJx2Evg/rDgF7xEG4EjtLv3lv0A982BxL33LCtNLGy8=,tag:j9YZpDfFpFXVaurxjxd5og==,type:str]
  NB_CLOUD_API_KEY: ENC[AES256_GCM,data:ywXbZN9c4CzTtxnnO/X9aiym7Rkowa6IiJ5Bx2Tj6c5J9eVv8lA1+A==,iv:pWGJT1JG1EO1fphM8j7y9PnsEHZWc8RiWoviZqzwWeA=,tag:aFcHKkZNtqMZCLJCf7+RtQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcXhaZ0x2VjJTMTVENkJp
        RDNqbzV3aklaVHYrZWNQSW45TjFmb01WK0Z3CjVWR1A4K3VYZWlGaTVxZWkydzlu
        OUJIdjlIaHZaaUduRkdtdFVHeitVM0kKLS0tIHNXQnRldVVscFowVnI1UGtKRlQx
        eDY1ZjdadGh1cGFJdnFhcGRCYXVWNVUKV0zUj6H1QG/LLe3KYi5c1auei8q5lNoY
        hP3CRegvJUK1u74s3PCa0z38IXVVX8g0tLprlJj7nV6Z8vLWqI++FQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T06:53:41Z"
  mac: ENC[AES256_GCM,data:SNblvGJcpz/8yLsln6xOqIULuCHNTlks0313zjsAIc763hwTefPv8v0S38sIAGBLpJjIDXj3HpB9Dvs4wR4UCv86a1KJj1iTim/pIK/BMNkv6I8QOrIxyEpg2FWmMKNKL6N0eDDvPQQ3DjKLKAfI/e0a0F4adPZD2j3KalV6+vo=,iv:F8lhtDvZ88RjrIV8zhC63A3UWyd4UMybZmO83gxCIG8=,tag:V05hO0AqYwKW5KiljNrdMA==,type:str]
  version: 3.13.3
