---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: "${APP_UID}"
            runAsGroup: "${APP_GID}"
            fsGroup: "${APP_GID}"
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: "9.15"
            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
            envFrom:
              - secretRef:
                  name: pgadmin-secrets
              - secretRef:
                  name: pgadmin-oidc-credentials
            resources:
              requests:
                cpu: 50m
                memory: 164M
              limits:
                memory: 512M
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: "/var/lib/pgadmin"
      oauthconfig:
        type: configMap
        name: pgadmin-oauth-configmap
        globalMounts:
          - path: /pgadmin4/config_local.py
            subPath: config_local.py

    route:
      main:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: internal-gateway
            namespace: networking
        hostnames:
          - "pgadmin.home.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: rfc1918-ips
            backendRefs:
              - identifier: main
                port: http
