---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: ntfy-secret
    template:
      data:
        NTFY_DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres17-rw.databases.svc.cluster.local:5432/ntfy"
        INIT_POSTGRES_HOST: postgres17-rw.databases.svc.cluster.local.
        INIT_POSTGRES_DBNAME: ntfy
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "ntfy DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "ntfy DB Credentials"
        property: "password"
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
