---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: ntfy-secret
    template:
      data:
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        NTFY_DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres17-rw.databases.svc.cluster.local:5432/ntfy"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "ntfy DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "ntfy DB Credentials"
        property: "password"
