apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:PfFp3Q==,iv:f9q5Erf3FW+S6kuMimVEDfbNcENSFfoetsEBc14rv/s=,tag:AG9SA+NR/MSruEv++xWN0w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0oeujxuwHnV151VmdSKAbn1oRfhR0fpNR6c++giFmQ==,iv:hVSoYN2BLo0BO/rlDC3nJGPFNSGrda6yKILB0JbGz2c=,tag:IvHfcJU+nulfxoza4uc5/w==,type:str]
    NTFY_DATABASE_URL: ENC[AES256_GCM,data:AM3lukR2uwnuTtVvXcBbA/76Q6/hhq2cOtVcktKBcbVIixPFEjPgdaMP34Dnh693vcIEj55heD0sFFt5MOZTZNE1hYbaMfkwoFaFiRW/CeguENkJrVslZW39hETPFc8l8FFB,iv:p2ov23XKyLJv/y0hgJFc7C7sm/h3tJpubatciREm36g=,tag:+Olv4FXFsOx+cUESSg+qcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya2xjVlhSRjJjb24xUGEv
            M0xQZlFMS0ZDTVRCK0t3OHF4WHl0VHR0UEg4CjBCeFNHc1VjUnY0TGpmY0xoOG9l
            NWdRMWp0ZWNTc216SzJqZDBzV3NIaVkKLS0tICtTMUY5aTY2dzd2TEVkOEFQZjJ3
            NlZVVkZPRmZWQ0JJZTlVbUVBcjd3YkkKwbqbfRlw0frBnadw3e+/nFpguwcm2xFW
            e5ULMHBkfYuY9OU7E5IwEk1EkhUMF1qRVj+uxS1xVyJ1izJg4vRQRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T04:43:41Z"
    mac: ENC[AES256_GCM,data:grcR9pLsUxIMpxiUpXFVBz1j6BlsGjFZ8lW6Wljnpmv3BFmkSHRY4tZcY8SUPNTxBKb6rSjB8g27pKEx+AYv4VHaA90RSuwTI7Qbq7iZ6oBAjwA5D8ZrcL0Kbma6vNEYCaN1rfkrdFhcDEAm5l+bDIbBaQMONgh84vdrpaKgBE0=,iv:Z5vBOBF5tP9G2+GXQO6v9zJsK60yFPSVmnLgmKLUgJY=,tag:I+Y4mdM12F3rYoDDwI4qGg==,type:str]
    version: 3.13.3
