---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app affine
spec:
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.6
            envFrom:
              - secretRef:
                  name: affine-secret
