# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-b2
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2NKTPDgDAA3223fb/qd2k3m2uGQLdPNsqedE5JMIDKMGRTV7/ERXm2/8QQRbG+5O7/oyCfkThi1WI0jykNDAHtCAFXNaBxm5o2PRcu9D8ac=,iv:wLa1utSrVh0SR2HJlUI+HXxtcty97KqZfdhxzd0DYDI=,tag:DPrcYUnvl71jxufIDs8dgQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bR6wBRsTMoZ+dtwaYFZulJZGydyIYDWGmTV+Ean1BtynQV2gzeVXKyeOsfDgsaxG9W2k+gEhD1x2SZGr6nvXfJAMLDc=,iv:lH5bZ7Ur6LBl7mGO9yPpm/K3/jv2rYoKjaAnZjjaJFk=,tag:InVAjjinOV7Uz+RNCrEaUg==,type:str]
    #ENC[AES256_GCM,data:ZAME97dHlUdlXvGj+nkWdSi7TJD0suzaN2JyD11h,iv:rup1fZOklva9IhCBAE6BEEmtDZlxg1r3PsV0ZC1GSVQ=,tag:YdedeYs/E5P/GjVtuos1rg==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:M0Gvj27OiEDuiI6L4XR443yAWz/BuhfG+sFzSElridbZFb07aC6zNA==,iv:Ey0O1hr2u2owDXh2hLVJfifGkVRrmtqM01+MklpSrRc=,tag:s45mIhbhFTBtgKfDXi/Z1g==,type:str]
    #ENC[AES256_GCM,data:ZG5drJsKnx3nrcrMRC6ByopQpTkwMHYIIbzilh3L4e5pzJFIh1BB9Ko=,iv:AL3o8JzBQihq/bGukuuWN7oRMT9FONXXPz8zI0yVeiY=,tag:hBzZ1hxh6s9bDjfHA3633A==,type:comment]
    #ENC[AES256_GCM,data:bQSU/2o8W8AqKjk7pi75ZEOl5IOlf90BhOF3t3uelGePXfpL+o2kw/jjI388mDGCRcg3QmcUDVPkBOoaCX7vJ/4lsU4XDg==,iv:KCqVD3tBnyq0CgyndmI/3PGSq1Nq4OhpyGa1pR0O0iM=,tag:APVG+Fbk+2WIGGl1D19aBw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NSkWpZa4KQhmJgJu1Ymxi4W6qpLE0FDVNA==,iv:WVU+feCXyyJLxqH8XWDmhey55mOnzPzSCvHT6mrt4Xo=,tag:bzaLCQvrmUqPvGpyRxQ4kA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ES/GYtJNEcTaQI6hk8ttg5AIXGFgt5OOALZTinMP2Q==,iv:FlseRGKAeLSErHV1GS2CqLRMA/ivT8dDPPWIFgVjigQ=,tag:7IFoT7U9LzLMypwiHWC/Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodXpudWdhaitnanVxcmRl
            QzYzTWRRRVFwZXpXelZ3QnBBSFVYZFpQOEYwCkhZMHNFa1plem02alZTU3VLUzBz
            b3M4U1hpVWZ5MnN5SFIvdWdrMWxDa2MKLS0tIDBQT2ZpSUFQd3BDMEhvMFpXWU1y
            YWFXc1FYNlZGZm85RS8wYVpFclg4ajAKaKP28XYUr4Kw6fzfcN4SL8lmBYVn0soq
            Dmhjb+Rhkl1uiJUyYz5pnxjkv++oM5sCOxvQibCpLYW3XdnJy1/apA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T16:22:58Z"
    mac: ENC[AES256_GCM,data:7faL71pqTVg4+EdE/hNTL3G06HFRcqB9XKOW9fJOtwyfKguKm+/XFi9iVr596KrHroUdcwVkJ+8gY+CDb9GvpvN+dujhe2VsC19YSrKFbeLuWVa3o3fPzcPcxFZGXXoLn8Sx5hvirziNWA1EkKUIQI2vLZEJnkKUb+IwybKI2WA=,iv:it1R2fgydziE2MbRpZtxgw6TmFEXIVPE0cweLmWQYUE=,tag:UJDyTTtaieljPIfnuiuAPw==,type:str]
    version: 3.9.4
