apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-tunnel
  namespace: flux-system
spec:
  targetNamespace: networking
  path: ./cluster/apps/networking/ingress-tunnel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
