---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrob
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: scrob-secret
    template:
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DATABASE_URL: "postgresql+asyncpg://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres17-rw.databases.svc.cluster.local:5432/scrob"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Scrob Credentials"
        property: "username"
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "Scrob Credentials"
        property: "password"
    - secretKey: SECRET_KEY
      remoteRef:
        key: "Scrob Credentials"
        property: "SECRET_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
