---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-selfhosted-operator-secrets
  namespace: networking
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: netbird-selfhosted-operator-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MANAGEMENT_URL: "http://netbird-management.networking.svc.cluster.local:8080"
        NB_API_KEY: "{{ .NB_SELFHOSTED_API_KEY }}"
  data:
    - secretKey: NB_SELFHOSTED_API_KEY
      remoteRef:
        key: "Netbird Service Credentials"
        property: "NB_SELFHOSTED_API_KEY"
