---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netbird-selfhosted-operator-leader-election
  namespace: flux-system
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netbird-selfhosted-operator-leader-election
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netbird-selfhosted-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: netbird-selfhosted-operator
    namespace: networking
