---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plainspace-db-init
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: plainspace-db-init-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "plainspace"
        INIT_POSTGRES_HOST: "postgres17-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Plainspace DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "Plainspace DB Credentials"
        property: "password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plainspace
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: plainspace-secret
    template:
      data:
        APP_URL: "https://space.${SECRET_DOMAIN}"
        APP_PORT: "3000"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.databases.svc.cluster.local:5432/plainspace"
        PLAINSPACE_EMAIL_ENC_KEY: "{{ .PLAINSPACE_EMAIL_ENC_KEY }}"
        PLAINSPACE_EMAIL_INDEX_KEY: "{{ .PLAINSPACE_EMAIL_INDEX_KEY }}"
        VAPID_PUBLIC_KEY: "{{ .VAPID_PUBLIC_KEY }}"
        VAPID_PRIVATE_KEY: "{{ .VAPID_PRIVATE_KEY }}"
        VAPID_SUBJECT: "mailto:admin@${SECRET_DOMAIN}"
        SMTP_HOST: "smtp-relay.system.svc.cluster.local."
        SMTP_PORT: "2525"
        SMTP_SECURE: "false"
        FROM_EMAIL: "plainspace@${SECRET_DOMAIN}"
        CONTACT_EMAIL: "admin@${SECRET_DOMAIN}"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Plainspace DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "Plainspace DB Credentials"
        property: "password"
    - secretKey: PLAINSPACE_EMAIL_ENC_KEY
      remoteRef:
        key: "Plainspace App Credentials"
        property: "PLAINSPACE_EMAIL_ENC_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: PLAINSPACE_EMAIL_INDEX_KEY
      remoteRef:
        key: "Plainspace App Credentials"
        property: "PLAINSPACE_EMAIL_INDEX_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: VAPID_PUBLIC_KEY
      remoteRef:
        key: "Plainspace App Credentials"
        property: "VAPID_PUBLIC_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: VAPID_PRIVATE_KEY
      remoteRef:
        key: "Plainspace App Credentials"
        property: "VAPID_PRIVATE_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
