---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      profilarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/dictionarry-hub/profilarr
              tag: v2.0.8
            env:
              PUID: 568
              PGID: 568
              ORIGIN: "https://profilarr.home.${SECRET_DOMAIN}"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: profilarr
        ports:
          http:
            port: 6868
    route:
      main:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: internal-gateway
            namespace: networking
        hostnames:
          - "profilarr.home.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: rfc1918-ips
            backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        globalMounts:
          - path: /config
