---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: vikunja
spec:
  name: Vikunja
  callbackUrls:
    - https://lists.${SECRET_DOMAIN}/auth/openid/pocketid
  logoutCallbackUrls:
    - https://lists.${SECRET_DOMAIN}/
  allowedUserGroups:
    - name: users
      namespace: auth
  secret:
    name: vikunja-oidc-credentials
    keys:
      clientID: VIKUNJA_AUTH_OPENID_PROVIDERS_POCKETID_CLIENTID
      clientSecret: VIKUNJA_AUTH_OPENID_PROVIDERS_POCKETID_CLIENTSECRET
