apiVersion: v1
kind: Secret
metadata:
    name: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:xP5NmesXL1cqppZLntWSeqE5TSsE/M/i8qOZ8l+DmKo=,iv:jjFt62WMPbfrEr+tv4o81b0HP5WnApSk+MQMbqTTMWA=,tag:An8a68xHm1kZ0SLHaDkzdQ==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:B7oZiefCFA==,iv:BT+2v10DgIS7qDfXR1eZwvKAG4Dp2kUh892vlFai8tQ=,tag:WQGwcY/0vzGPB7GnMQWYYQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:mV40rMJqBRk/xF7HkuZRPRp79oQzYPpnWxvk3TvPIz4=,iv:Pc5T+RfgrCzgbgkV2nfsKiKnyoENt5+XTUaneKev5u0=,tag:Bpf/i8IfylPpmVWe4lcpNA==,type:str]
sops:
    age:
        - recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaVJuTXM0bkZFNU1tT1k2
            QVpDQXVpbWJrWEQreEREcjRSZHJqckFBN0ZnCkRXTVBCek0wY0MwYS81bHdxRDhm
            VHNVYTFWazFqeW5heVlUV1dXOUtxMG8KLS0tIGw0S1BaR2JkdG15YkQvOFA4U2Ja
            dE9xa2NzeTJDRllVbEVTMW1jNXdmUEEK8ljSQOvDrUsB4C3FwMPKzHKhYpfCV9OG
            P2Nu9eItbEEh4TuVetDdLgftF2xuu5TXgsaADiSKIfwdSIdCWrVU0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T17:24:02Z"
    mac: ENC[AES256_GCM,data:Cgq0OFewXmCPosf0MCQ7hVYUbwQRb/xcRP6qhXRXIQGwSMi+Ipb8mNL9IBvFAzUr/WmxaMCmxnbVqCkHK/1j24els66m/DaHbndigoLc+XfLGvzfyJ+qPvJHslSqVDWUhaXugUwGY46Gtc2knpCghSfx5ZCXHfcvYb+Bi65JgWE=,iv:DHX2ATuxTVWijQZNZ5etXVPEHjmIlUjCKBHGAsU4ptI=,tag:+ohX+EsYyD9IEX7ayohl0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
