# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        # s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 44
          - 226
          - 568
          - 65534
          - 65539
    controllers:
      tdarr-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.82.02
            env:
              PUID: 568
              PGID: 568
              serverIP: 0.0.0.0
              serverPort: &serverPort 8266
              webUIPort: &webUIPort 8265
              inContainer: "true"
            securityContext:
              allowPrivilegeEscalation: false
              # s6-rmrf: fatal: unable to remove /run/s6: Read-only file system
              readOnlyRootFilesystem: false
              # s6-applyuidgid: fatal: unable to set supplementary group list: Operation not permitted
              #capabilities:
              #drop:
              #- ALL
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: tdarr-server
        ports:
          http:
            port: *webUIPort
          server:
            port: *serverPort
    route:
      main:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: internal-gateway
            namespace: networking
        hostnames:
          - "tdarr.home.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: rfc1918-ips
            backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        globalMounts:
          - path: /app/server
            subPath: server
          - path: /app/configs
            subPath: configs
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      shared-cache:
        existingClaim: tdarr-shared-cache
        globalMounts:
          - path: /temp
      movies:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: /mnt/user/Movies
        globalMounts:
          - path: /Movies
      tv:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: /mnt/user/TV
        globalMounts:
          - path: /TVShows
      other:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: /mnt/user/OtherStorage
        globalMounts:
          - path: /other
