---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 41.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    gatewayClass:
      enabled: false
    gateway:
      enabled: false
    deployment:
      kind: Deployment
      replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik-internal
              topologyKey: kubernetes.io/hostname
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIPs:
        - "10.0.10.30"
      annotations:
        io.cilium/lb-ipam-ips: "10.0.10.30"
      externalTrafficPolicy: Local
      ipFamilies:
        - "IPv4"
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: "traefik-internal"
    additionalArguments:
      - "--api.insecure=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.kubernetesgateway.labelselector=gateway.sysinfra.pro/type=internal"
      - "--providers.kubernetesingress.ingressclass=traefik-internal"
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        ingressClass: traefik-internal
      kubernetesGateway:
        enabled: true
        statusAddress:
          service:
            name: traefik-internal
            namespace: networking
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    ports:
      traefik:
        expose:
          default: true
      web:
        port: 8000
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
              permanent: true
      ssh:
        port: 22
        expose:
          default: true
        exposedPort: 22
        protocol: TCP
      websecure:
        port: 8443
        http:
          tls:
            enabled: true
            options: "default"
        transport:
          respondingTimeouts:
            readTimeout: 3600s
            idleTimeout: 3600s
            writeTimeout: 3600s
        http3:
          enabled: true
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 192.168.0.0/16
            - 172.16.0.0/12
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
            - 192.168.0.0/16
            - 172.16.0.0/12
    metrics:
      prometheus:
        enabled: true
        service:
          enabled: true
        disableAPICheck: true
        serviceMonitor:
          enabled: true
          namespaceSelector: {}
          metricRelabelings:
            - sourceLabels: [__name__]
              separator: ;
              regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
              replacement: $1
              action: drop
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              targetLabel: nodename
              replacement: $1
              action: replace
          jobLabel: traefik-internal
          scrapeInterval: 30s
          scrapeTimeout: 5s
          honorLabels: true
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    resources:
      requests:
        memory: 110Mi
        cpu: 250m
      limits:
        memory: 1500Mi
