# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:So7U90KEuu9cf14S4gmtVSHkFPaDXZoPgNHbXGW6fMUZmiN+sGisl7f6a+hPfspW/RuByMkC28yTq+maHBObTA==,iv:lW2WO6CCyti9TpAx77cK5m9Ud5U33fvKSq40wMQyU/4=,tag:BCuPBXAJkA+tb54KOGC07A==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:YkEFgR63to4nnKA8Z0PH9Riu6lqN3IDM8pcmgb7phOtKg8IXjU64O6aGz7RG8E2FKQwRjHphLjbR//QpP7qhMg==,iv:qOp9GEYuHc/lVuAB1iho7ALKROA7x674NlQ83BsHZbM=,tag:puGvWSSZY/pCs1OVRe91sw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:hVsrp1XlQtjjHpeCryFCpKdOiIEzw5xE+tbf4ncvHR9Gxq70dDxl7C6lsr5EC9BJfRgAcL4S2cEF3uSKoIaH1TFn43bT8tuEQMbt/hQlJSWiuoyOB6EKSWE+xTCBsRPI0UdGeOaS3Hty+wWO2b8ZmZ6JyGXEI6uT9SqWxA1+xvOT,iv:R3AoC2b/xhHts8WVNlKIlQumXcSqm3lyRFWMwUyqYSU=,tag:0s4EBnTad+E3Rbv0/iYMWA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:MUVMuaS/0PnFr492,iv:QsSRV95bj073Ahhn3Y07hDH7sJDAGBpuZ+kRAL9Znxc=,tag:vyNGah1HWLZKTWKjS8xkpw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tULJ+oBSgH/38C61LFUufZedFcJjeCyJQexmoWsKi0kPuedsRyeGH4vKeGbLSEZc,iv:lAmRvVOcidQn1C/NiPYb8nIt0pzem42d6NYBGlLEtAI=,tag:ve3WBcP993U2A5PHH0wkYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRjYwT3FmV1lXT29QSkx3
            K1o2WTlKQW5oT20vZEdSUTFRWCs0aWRST21ZCm5KMzNXMTQwS3lqOHhQWTFkb0Uw
            cndXaTJlaDdYQUFGQWJValgxMnlpWnMKLS0tIHkyUyt0SVdsNHd4VytvV2FmMW85
            T1ppK1RIdkRWU1RDVk9ybHY5a2F3Wm8KukGGbFVpSfpCex5mrriTf1kZiiCts5Sg
            sIN+H8re6tBDhIB55XwGXEOXGjkQzZGZyoLEmztR2vGbHr5IPRKheg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T16:30:11Z"
    mac: ENC[AES256_GCM,data:gu1vbsAbsBGTaMUumTbSrIrSj7TKArUrl8VpxbV0ACmSYuQtmZhrysGgu08+pXwu7q6XEsHvoaZ4o3qUtPGVWzvrV+mAXgt55FmeWgQWeQcVkxigvzwA0N7vtnXa+k+x4+WeSM997N8hFRc+Vs4jSnIX8Xvd5g2bMIBKdWnOOts=,iv:R2ajYSmOBGKI7ntAImNGO0a/eMXKfbyw+DrT/1cFwls=,tag:Hnk4P0N3817bnd4zmVQa5w==,type:str]
    version: 3.13.3
