apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo-chart
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: depName=codeberg.org/forgejo-contrib/forgejo datasource=docker
    tag: 17.1.5
  url: oci://codeberg.org/forgejo-contrib/forgejo
