---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./dragonfly-operator.yaml
  - ./headlamp.yaml
  - ./forgejo.yaml
  - ./forgejo-runner.yaml
  - ./pocket-id-operator.yaml
  - ./ceph-csi-drivers.yaml
