---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: stirling-pdf
spec:
  name: Stirling PDF
  pkceEnabled: true
  launchUrl: https://${GATUS_SUBDOMAIN}.home.${SECRET_DOMAIN}
  callbackUrls:
    - https://${GATUS_SUBDOMAIN}.home.${SECRET_DOMAIN}/login/oauth2/code/pocketid
  allowedUserGroups:
    - name: users
      namespace: auth
  secret:
    name: stirling-pdf-oidc-credentials
    keys:
      clientID: SECURITY_OAUTH2_CLIENTID
      clientSecret: SECURITY_OAUTH2_CLIENTSECRET
