apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:R+bJdr7MoodixF7Q0LqTrYYvnkzu1+t6mzE9XRhatBw=,iv:dalWUPWLXb2UocEf8gvtHzg9XkQFEwe+kx1D7IRLl4k=,tag:cBi14FELx4OXFKfa9JaUZA==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:cYvnyFZoI+QB,iv:aCpUXZN4w1XJFymtXsZPfayEeQnc+gO5fdEeZaRRSl0=,tag:rvouJYqMAXZW1O5bS6uVDg==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:CkSf/hFR15iL,iv:Rz20kMzvhMLf/FX7OlQPsdwVkIljaxQvujnsT7Na+Wg=,tag:QRJTv/H6X8BXM9nglEpyLQ==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:euqruRWNb4MQZXeJQ7wY2S6fZ9idzQheucQSWjAXusY=,iv:cg7YNPW2qNA14Ae1sSxyWxUJp+8LAtYAdoPdOklfWr0=,tag:u59WnAhA01IYCJKMnCeZOw==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:5iqKRSk2O7yF,iv:m6Je30ysQuu2JRowMo6EGQ2EWSi2RU0AXsPibWuHEVE=,tag:t84HHKhXB/e0ErlV72DRPA==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:o019AoXYFM3P,iv:gvb5f3JsfNkqNfq6qQxnEGOWVd2BRWSFmb6XSMx/ahg=,tag:Vk51C+eySA/E5j8VKYErnw==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:afGibPBfT0omWJXw2+ZhSUo75fMEbUFfr3ZCW1+dwV0=,iv:kGL0PyU/JG7Pt6D2WdpYb3F+MdxGn1Gum75Zm2ay+zE=,tag:VPs/GsYreQJuLliquEmxtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcEZrL0syZTd5empQQVh0
            UVdYWVRHNllvUDJDTnNLblFGQ1lGZjNkZ1h3CnBYckNQOWZuZlkxQnE1Rno0VUYx
            dW5vT0VBSHp1b0l4Nm5jcWJGbjNJTXMKLS0tIDNrQnprak9mUWliOTQ4b2dQWUVT
            dGdoY1R4MzNXeFFDOS94djF6OXRPVzQKGJx1VkBejynx2Gh+o3DK253XaVCI7QBZ
            gGE37ZfAM8YxckobaMDd9ki/VuWhSyRncxeqhzWSg4+mvHCnzo8UPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T21:31:17Z"
    mac: ENC[AES256_GCM,data:UZz8fhaDscgiqbjg7KGPqvekfo23T73eD4mrY8dElQ5cnaEWpA00njEdWckNRMP+Q6jb6DTehV5ZRfAFLEnrL2Z1E8HAipy1rTf+Lg+s97DRKksJf7u6lMe5AvmsA7dzEfxRkrOKxwWuQaIywpgxVmrcKOCONApPu1c+9E9UsaE=,iv:FRzXhbU46QMcfctGUdbexUwRKyY7ZVWHXgII5A73LcY=,tag:mL3LHMXk1cfmMrx+SPEkLQ==,type:str]
    version: 3.13.1
