apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
stringData:
    .my.cnf: ENC[AES256_GCM,data:NNImlDlnPFETXuCele5whkIi4E586yYTmiIVCA0PC+4a4G+s/A2Ph8W3FsJo0z1SLbb2Ej7lKVAgll0hMr810wMYVXjSCCRZQNeLuevDx8vdbyVD9UJU9yZgTECN3KYCiTtX,iv:N2dj24uchjO29fqMsDhn9OcYvzxaOyaTuq3C/W8fvz4=,tag:Kzj3kK1BWBhWnGXcOyeFqg==,type:str]
    DATA_SOURCE_NAME: ENC[AES256_GCM,data:ekDoo8kdd0GZ8haKY+NEBzFWRTGRf+thY2bCH8wWTRV8RnXENzVR/ZR9vCNQwCNxPoZJMSfFGwYAYN0tJERYzSKCTpVv,iv:qquNuPlzVXeUJpxlpcjeoAPV+d1Hqo11vvRCbNhkucM=,tag:Xa77Xrskx3CQo/on8hnHzw==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:TmBHf4HCc+Rk,iv:oHweorgh0fR/Y8zqgp08r62WPN4alazYQSQg1i9b3Rw=,tag:sxkSmjebEdhY3MoOPvwQqw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:uXepeQbck+6Yek56cLOV/h3PohDuqB9vIzyL2noEy3M=,iv:CH9JGbSdyXtrzyDiqtrajHObzi37Qjk4EbLyvwbH1Y0=,tag:EIgkYsbMjS0xV/bpDy9Aug==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:otvPI+jW33zFGmbzWcFG5R+cAfARJ18zAAgSUZVrJ1M=,iv:XhN1ec0q/Ssmf7hfqZk8M/5t4q9teJuiF0V0uBHyAv4=,tag:mrYzdfLSddVcA9LN4cs+Yw==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:3Da76RiTypmJ,iv:iQ79gqhll0/2rXd5LchbuhuPwo3FICAMIy8535wUQ0k=,tag:BEkq5kcj4w0WlDDzkPvCvw==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:UA6paiZGfxWW,iv:q54Jt7dxcQvzTJkjcTNj7vvABTJu3HQl2WJZ9EyBbh8=,tag:t55eEI4CuDA79ZflaLArjg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:wE9n6Ay0PNYpFtGPHehetdtlJYAR61rrbonJInmacds=,iv:+kLxtn2FYgP44ZYGMmaWTEdYjAKK2ft9J6hXxiWI4xg=,tag:fY4OKeVKVjUatKQTbdzLzw==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:ptY2kkEYzcbe,iv:RZDaTsN0FEb7oNOoPjYU287tSShWGJfvW1cb1RIMFNI=,tag:ljUuGb4xOgQtu69FY3kv6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd3FzZlliMzVuam1LdGhI
            ZjFvS3Zub2JNWUE3WTZFMlJyZVdtckpKdmhRCm5aUDVlaHBIcEVoNm5TcHZ5bXdh
            YXdXL0dROGFFYUpXWlBLbE0rVUhvNkkKLS0tIDgwQkN5UUswOWl1ZXp0dkxudEpZ
            UTlKVWVhR1ZaVHRoUVNPb05WUlNReEkK4PMqvCMThE/vGF3vND+g3DYtZnMIjYVY
            nuQ4L44YzFABukKxRBHf1HPxa3OIji2h8ZIgSCQOHyyoiEVQ+P06Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T22:28:27Z"
    mac: ENC[AES256_GCM,data:n2IG6ekITCc6mjhq1j7cJnpZ6i281Kdj8XI9aOFKDhF7Xc6ateoWeY4rN9hp2Sqm9p8zdvRJFICb3WFlF0YosQkakNk0jqqnvxdkozC2p7l4B/WL6fi+cgk4z5MRSVZhVYCNWbTR2/Qicfp3RCx+ORcPKKitjStm+TrWkaM3pws=,iv:WBQh3GtfJ8DengGPqbMylMY+ZKju0Rm+kVzZOhNcVgc=,tag:OBMBsv/lPRMMoGB1vgl4Fw==,type:str]
    version: 3.13.1
