---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            supplementalGroups: [10000]
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: "4.0.18.2976"
            env:
              TZ: "${TIMEZONE}"
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__AUTH__APIKEY: "${SONARR_APIKEY}"
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: "https://sonarr.home.${SECRET_DOMAIN}"
              SONARR__LOG_LEVEL: info
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 22m
                memory: 1G
              limits:
                memory: 4G

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        enabled: true
        annotations:
          gatus.io/enabled: "true"
        parentRefs:
          - name: internal-gateway
            namespace: networking
        hostnames:
          - "sonarr.home.${SECRET_DOMAIN}"
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: rfc1918-ips
            backendRefs:
              - identifier: main
                port: http

    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
      downloads:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: /mnt/user/k8s/media-downloaded
      tv:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: "/mnt/user/TV"
        globalMounts:
          - path: /TVShows
      backups:
        type: nfs
        server: "${CORE_NFS_SERVER:=nas0}"
        path: "/mnt/user/backups/sonarr"
        globalMounts:
          - path: /config/Backups
