apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    #ENC[AES256_GCM,data:Lef7DVbkIs9arE2ITVPKklJ6Y8u02a6bqWBdHjnBwampOal0uLbk8bN0SLnA846ysSFJqK2D7WVFtf29Yn8E5CTrGwstLVwFikGoTJImJOOaBGG2hQZqC2K8MxEvxyMkiH9a/wkkJqPB+Slp01TtGXCgzsgchvIJ52s1vfqpufkrqZqbVvdfboqoPEAbE3BF1PUkOaMvtKsZ+FhZdyo=,iv:bBSnKPhty4R6A8a8GtyXH5dwah5YJnBzs4gGgJHdBdU=,tag:8SW1AwDnndjNOLk1Nzbcqg==,type:comment]
    #ENC[AES256_GCM,data:mUSitih0NUE8MeHKGY4EdXltuYVEa/RXbojFjhc4WP1pi9PBM+dfwLDrxzPnMNAELPW9Ckd9QzlGIGbBb8XCcMLR3Vj26s6m/LW2OiP3TYa0+v4Ai8GlGUVkYyUudIdg5Qm6PaetsGkPQVvem2TsIVQ/15MA2s1TpT0hFxD7,iv:qYXKzxo/Euknc+mlGkO/oi8dYk8+NvOzBDuz/H2/blc=,tag:5Msa35kLk/bSJ3CSwoKBmw==,type:comment]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:OIhcRLh0Md61Q8zAZ6RlwaukHFaJPG+toIWFjkUxU5tk3daKMaOVgV3TJAihwKUdtT7CX9zCy76ViKbe0YFSfXEkqs+48kEEiTyrMUnrl/bsNBTktvEmQDQYycOJJIvPAr3+AfeXPzsSIshza0cRd5BO30fJBTzXHiI5WKZK6Leib4NOI/kD6J3dx7DB8UGfG2aeefbp3jiHvLGiw+rlNfN4ovaGlh4MFxjVaQ/UKgUWOfRC,iv:8M9/YOwoiOqDGIcix4mf5dUCMAnkIiKnsUPwMhidhdg=,tag:IDvgOs7zvVyVmqlxyPfz3w==,type:str]
    #ENC[AES256_GCM,data:sTIxWVahBacXmTx8Cp10UqKrMJ8H/ectU/y1XgkcaypkqHKkEWWHco9YAT3iDQX0,iv:ag885Icp7/EoPncRZvK0CaetDnMMnF3JzL71NwK0GIE=,tag:CynZiXSyzEftdmckyVzG2A==,type:comment]
    credentials.json: ENC[AES256_GCM,data:UtNRL6tZv47v9WXy5tCyYlecTUa4tYkSbNuwRhSJV+WaHFgCWf2NymX3453HWITtQUchUBrAaoy/zXxj/exO0Rkv1oaKBD2ygUC9tHDm9gh5Yufd+7W/Rk/suDQINCAgSZlsdCpjq2oWY69X/wcofiMspyFuvNnbFlHk3mBTzYsck6FUeZaad0nYe9lvD6vco8v75JoxVYIZUUEwLParIzk=,iv:/yXzIK/FMXLHqVtLtTfqomTaHsjYEOSSxpv3rZgxYO8=,tag:j5avUDjLsgA5hp6ZTrMGFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NU00WElhaUd6NkErTG85
            NmNxQ0g3bi9iNFl1WGJDTFJBc2w2MVU5S0NBCjYwUzdubnBXSkJ2UlRyWXRHcU91
            LzM0TEZ2ck8vTnZSS3p1QjRqTnJlYkUKLS0tIE9tR0lBR2xsYlR4bkxTdXVNQ1hE
            OTVpbkpPSisxNnBxUCtrRzdoRWJLM2cKlT96WAcQt6L52I6xSIhaQ+4uWVI9+gHq
            9FnhZz2FI8mmG4O1iL99o/k4bvOE6KiGQQnvAaHJLE3iiuMb7mw+2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T05:54:44Z"
    mac: ENC[AES256_GCM,data:3Zrvq08orWxlQ/gNnyu/lNknYJJFjtKhcENx9zNxkXfYlG/wpDhqVfkbey3zePyWFu588xWDRTJc9dJn+AkVYeDF+9yz5MRcqGU21cg/TP3mb3nUeG9zdLnwE7CDAAJKM74YhBD5WFNrY2dVrujNUAcKAl6ErJNvtVJF50XF7wM=,iv:0D8m06ij0JSOvMCfY+XEf16kEyRUkUvgN7K/l/52Xss=,tag:kWQEE6MMDw4VrykB0dGtlQ==,type:str]
    version: 3.13.1
