---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: headlamp
spec:
  name: Headlamp
  launchUrl: https://headlamp.home.${SECRET_DOMAIN}/
  callbackUrls:
    - https://headlamp.home.${SECRET_DOMAIN}/oidc-callback
  allowedUserGroups:
    - name: admin
      namespace: auth
  pkceEnabled: true
  secret:
    name: headlamp-oidc-credentials
    keys:
      clientID: HEADLAMP_CONFIG_OIDC_CLIENT_ID
      clientSecret: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
      issuerUrl: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
