---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: headlamp
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
      app.kubernetes.io/instance: headlamp
  endpoints:
    - port: http
      scheme: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
