# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    pushover_api_token: ENC[AES256_GCM,data:du3Q0cL412svEaPoDpF3KDfxOxwZieRz39vcxT0U,iv:M44vKcVDkMgQnRJDE8dirdKZOUze+0gYsQ7pJBCMo8c=,tag:klVn8NRv/7Q88UHBWaPSeQ==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:Hni/v5AkirqNe0MELNrBddqjcAxSsFVO16+MOJI4,iv:nCpGzmAcKEdR47VRuuBYe8BwbRwP+Lcf84XpVWnBS0g=,tag:py7ACtMTXU1fnbWOZgK+JA==,type:str]
    ntfy_bridge_webhook_password: ENC[AES256_GCM,data:tP4hrvT6lQiu/Y3/mgojL0GyZed7rBz66MM0A5ez,iv:kTEbN3MiTdMKteq/xMrk/YiVkYg6VOIc00UaS5gBnJM=,tag:SQ1Z1IGXh67eijfjImUsHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeWlxRitwMGVaZ0hCdDM0
            U1pMYXZzUkpqWkxmc25rTW50SE1rVEZIaFhJCktBM09UTHdFK1lvV2xDWUg2QXF6
            ZlNaLzVnZGFVdlpEdTB3NURBNm0yeFkKLS0tICs3SUtsUWhCN1FFZm5ZSHRoSms0
            bGJ6SmRVOTN1SWJScVpJcEhoSFdTSmMKVpE/EPMRQAeygVfFkBib0IiUTgbQxifZ
            u0gsKMr+wHItAcAwMNr2mBUl0nsk8gCbBm53Ar2BGnLx0+7WQvPXuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T06:32:49Z"
    mac: ENC[AES256_GCM,data:NXVPwPtSvTZJdBXak+GroQk2AqmJ6oU4mqWGM6u/VK/qMeS9oLkJ2GteGCuLxfJ7KhQG+mKmIro843Dhw72QnIoLCewlFpj+2gBFgXZ93C47dkYxV+CU8hGioQs/pwUQVNArRrVqv5h3XscFiERFnyDARs5ZrttPTawQ2YyQ1h4=,iv:/ZY/kTp8D2N73d78TDNg3MTULfjRsosiNpJ4mTWQ0GI=,tag:HQsreuCCb/3o19PEqr1tVw==,type:str]
    version: 3.13.3
