# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    pushover_api_token: ENC[AES256_GCM,data:d6zjqSn2T5iVnK/kohC8lqHKjAV0B5WZjeSMSmNV,iv:iM2uvNj5NFLd1SrmHn/u6dtI0V1To0E7uEPGT5vDGuY=,tag:9EuLThU+FiCL5aCUFvokjw==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:1HpUxVoWCP6ijD1lxHl2PIF2+Ra2ETR2da/vIQ3q,iv:NMHDIdOyLrWeReiiRh5TPAFmplXMfbAVaq+H62m0qZA=,tag:IHPBKiH7NjebDpcX6/mMSw==,type:str]
    ntfy_bridge_webhook_password: ENC[AES256_GCM,data:/E9cJFKDGN6qgJru4nm+0q9AKByGYos+Tu7mzjYEFm4=,iv:ANnW9iW3BZ2Rjp9Ah8TrxqJwKMAy8njEEUHXYFzf9RM=,tag:ix3fPd7K0YvCNg1liImGAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbGtrRHFCcWJhRVJvdU1M
            bTFRajkzRHBKeS9TTGRzeCtVU2FhbWVqUkFFCkdkUVdSSmN4L1dVd1BqdkJIa00x
            UTBWbUk4MWhhTEFPQlVPL1BUZ2RHL0kKLS0tIGk3S28yKzhyUS9IRG9ZMS9hVzR6
            Wlhhd2FwYXlmQUhCbUN1L2luSGNQZEUK6grc8fLEj2vzG82lq8/AtqZDiyqO/uJO
            Q7wemAYW9ov3xwIdp04cxI1Stzj0yaUJCBtvEnPSHE4I3TFLsqmnww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T06:26:00Z"
    mac: ENC[AES256_GCM,data:Fw7z7JP/7APUAQE938I0oS970rnqPHKKsaD+e5cCo0382EyN/FJxKyUINRHqIljqr8hf4iavQszcxPl4C4QEHV6uGJQeRXZwQ0WWPK1kvZeYjM9CinP5//Ja49bwjtV8s+e45sEL4q7wegoLPZpu3IbjQL+LzunpsYsJnHp0W8c=,iv:EnlE9XkTrzymObm9JLt1kt8iNbpc7RXXhcvflsC0kIc=,tag:l3jeQX4heGeEPbipJumQKQ==,type:str]
    version: 3.13.3
