# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      ntfy:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.25.0
            args:
              - serve
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
