---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-creds
  namespace: system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cloudflare-api-key
    template:
      data:
        cloudflare_api_token: |-
          {{ .cloudflare_token }}
        cloudflare_email: |-
          {{ .cloudflare_email }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_token
      remoteRef:
        key: "Cloudflare Credentials"
        property: api-token-external-dns
    - secretKey: cloudflare_email
      remoteRef:
        key: "Cloudflare Credentials"
        property: email-external-dns
