---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-api-nginx
  namespace: system
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 8087;
            location ~ \+ {
                rewrite ^(.*)\+(.*)$ $1%20$2 last;
            }
            location / {
                proxy_pass http://127.0.0.1:8088;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
