---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-rate-limit@kubernetescrd
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-cloudflare-tunnel@kubernetescrd # from the real-ip plugin
      - name: networking-traefik-middleware-compress@kubernetescrd

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-direct
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-immich-rate-limit@kubernetescrd
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-internal-no-auth
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-rate-limit@kubernetescrd
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-pocket-id
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-rate-limit@kubernetescrd
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
      - name: networking-traefik-middleware-pocket-id-forward-auth@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-cloudflare-pocket-id
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-rate-limit@kubernetescrd
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-cloudflare-tunnel@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
      - name: networking-traefik-middleware-pocket-id-forward-auth@kubernetescrd
