---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-db-init
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: dawarich-db-init-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "dawarich"
        INIT_POSTGRES_HOST: "postgres17-postgis-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Dawarich App Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "Dawarich App Credentials"
        property: "password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: dawarich-secret
    template:
      data:
        DATABASE_USERNAME: "{{ .DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: "Dawarich App Credentials"
        property: "username"
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: "Dawarich App Credentials"
        property: "password"
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: "Dawarich App Credentials"
        property: "SECRET_KEY_BASE"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
