# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-pg-meilisearch
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:QBLwfSRzExGk4l0ROdFEeRtrkcJlsH8VBA==,iv:qQ0AXnv8xfoVj4EEszqmi/Kkmo+upECg2wNPydi/h0M=,tag:5jMN6kE8YbaSbXaf1MeMIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZmtRdC9DZGJDZWJEY0Ji
            L1UwOFpscVlOLzBaMXFXVERITFIzbFgvUUVNCnlZU2liSXdKNXR6elFLSE0yWTZa
            L2xWRVNqSXZ5SEljMDYrbTdFNVMwSFEKLS0tIExaTmU5MTBZWWNueWRaTHZ0WGJI
            TjlvR0V4ZThCT3pjNXhSZXgzaVBrS0UK+FZQG93fs7bqCd4iDTLXd7SZSuRPgksx
            WBeG+RKVOzHjJGtBDYj6P056/Us6lEmiXXoA94zwNaH9+fe8G3+dWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T01:21:46Z"
    mac: ENC[AES256_GCM,data:ifYUFup3ecI5ZtMP5SpswAH+ud/TUeH23RszWI+dnOM6GLPuZBqGsOli2jSmwRtQerCZFKY/3vw9KNJYzW8R7p3t19pDtygPbJ8ml+rqnRdlRLU6oXBuFKWZRnnSti3shm7q8wyzWm/28LgQjX+I064TJ3ioW4A8khXuNdun/O0=,iv:2DKHBoZDZD+Ylii+6iYxPsiLnw6nLsQZ/oPbcZXBtt0=,tag:FZAYTtBluGF7ILoYE0pejg==,type:str]
    version: 3.13.1
