---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-operator
  namespace: networking
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: towonel-operator
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    towonel:
      apiURL: http://towonel-hub.networking.svc.cluster.local:8443
    credentials:
      existingSecret: towonel-hub-secrets
      tokenKey: TOWONEL_K8S_OPERATOR_API_KEY
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
