apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-tunnel-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: ingress-tunnel-secrets
    template:
      data:
        hcloud_token: "{{ .hcloud_token }}"
        ovh_endpoint: "{{ .ovh_endpoint }}"
        ovh_application_key: "{{ .ovh_application_key }}"
        ovh_application_secret: "{{ .ovh_application_secret }}"
        ovh_consumer_key: "{{ .ovh_consumer_key }}"
        ovh_service_name: "{{ .ovh_service_name }}"
        tunnel_handshake_token: "{{ .tunnel_handshake_token }}"
        smtp_server: "{{ .smtp_server }}"
        smtp_username: "{{ .smtp_username }}"
        smtp_password: "{{ .smtp_password }}"
        admin_username: "admin"
        towonel_hub_link_psk: "{{ .towonel_hub_link_psk }}"
        netbird_setup_key: "{{ .netbird_setup_key }}"
        netbird_selfhosted_setup_key: "{{ .netbird_selfhosted_setup_key }}"
  refreshInterval: 15m
  data:
    - secretKey: hcloud_token
      remoteRef:
        key: "Hetzner Credentials"
        property: tofu_api_token
    - secretKey: ovh_endpoint
      remoteRef:
        key: "OVH Credentials"
        property: endpoint
    - secretKey: ovh_application_key
      remoteRef:
        key: "OVH Credentials"
        property: application_key
    - secretKey: ovh_application_secret
      remoteRef:
        key: "OVH Credentials"
        property: application_secret
    - secretKey: ovh_consumer_key
      remoteRef:
        key: "OVH Credentials"
        property: consumer_key
    - secretKey: ovh_service_name
      remoteRef:
        key: "OVH Credentials"
        property: service_name
    - secretKey: tunnel_handshake_token
      remoteRef:
        key: "Fast Reverse Proxy Credentials"
        property: handshake_token
    - secretKey: smtp_server
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-server"
    - secretKey: smtp_username
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-username"
    - secretKey: smtp_password
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-password"
    - secretKey: towonel_hub_link_psk
      remoteRef:
        key: "Towonel Service Credentials"
        property: "HUB_LINK_PSK"
    - secretKey: netbird_setup_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "VPS_SETUP_KEY"
    - secretKey: netbird_selfhosted_setup_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "VPS_SELFHOSTED_SETUP_KEY"
