apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: towonel-metrics
  namespace: networking
spec:
  jobName: towonel
  targetEndpoints:
    - targets:
        - "vps-primary.${SECRET_DOMAIN}:9090"
        - "vps-backup.${SECRET_DOMAIN}:9090"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
    - targets:
        - "towonel-hub.networking.svc.cluster.local:9091"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
    - targets:
        - "towonel-agent.networking.svc.cluster.local:9090"
      scheme: "http"
      path: "/metrics"
      interval: "30s"
      relabelConfigs:
        - targetLabel: cluster
          replacement: towonel-ops
