---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: mcp-postgres-secret
    template:
      data:
        POSTGRES_SUPERPASS: "{{ .postgres_superpass }}"
  refreshInterval: 15m
  data:
    - secretKey: postgres_superpass
      remoteRef:
        key: "${BW_POSTGRES_SUPERUSER}"
        property: password
