---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-forgejo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: mcp-forgejo-secret
    template:
      data:
        FORGEJO_TOKEN: "{{ .forgejo_token }}"
  refreshInterval: 15m
  data:
    - secretKey: forgejo_token
      remoteRef:
        key: "${BW_FORGEJO_CREDENTIALS}"
        property: password
