---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-home-assistant-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: mcp-home-assistant-secret
    template:
      data:
        HOMEASSISTANT_TOKEN: "{{ .token }}"
  refreshInterval: 15m
  data:
    - secretKey: token
      remoteRef:
        key: "${BW_HOMEASSISTANT}"
        property: "token"
