---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-cloudflare-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: mcp-cloudflare-secret
    template:
      data:
        CLOUDFLARE_API_TOKEN: "{{ .cloudflare_token }}"
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_token
      remoteRef:
        key: "${BW_CLOUDFLARE_CREDENTIALS}"
        property: api-token-external-dns
