---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-arr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: mcp-arr-secret
    template:
      data:
        SONARR_APIKEY: "${SONARR_APIKEY}"
        RADARR_APIKEY: "${RADARR_APIKEY}"
        PROWLARR_APIKEY: "${PROWLARR_APIKEY}"
  refreshInterval: 15m
  data: []
