---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret-github.yaml
  - ./externalsecret-home-assistant.yaml
  - ./mcpgroup.yaml
  - ./mcp-kubernetes.yaml
  - ./mcp-github.yaml
  - ./mcp-memory.yaml
  - ./mcp-flux.yaml
  - ./mcp-home-assistant.yaml
  - ./mcp-arr-stack.yaml
  - ./mcp-searxng.yaml
  - ./mcp-victoriametrics.yaml
  - ./mcp-grafana.yaml
  - ./mcp-kubesearch.yaml
  - ./virtualmcpserver.yaml
