---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-grafana
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/grafana/mcp-grafana datasource=docker
  image: docker.io/grafana/mcp-grafana:1.0.0@sha256:5efeafd01cd7e1aea9c4b0f03305951f2944db8f43e5ae290cce9578c977f241
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  args:
    - "-t"
    - "stdio"
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.monitoring.svc.cluster.local:3000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
