---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-flux
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-flux datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-flux:v0.1.0
  transport: sse
