---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/isokoliuk/mcp-searxng datasource=docker
  image: docker.io/isokoliuk/mcp-searxng:1.14.0@sha256:9af77b4fa75b933ef0a3ae49f4ddf086ecceaccac5740bc595a6174b2f0d1a26
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.ai.svc.cluster.local:8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
