---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-kubesearch
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=ghcr.io/perfectra1n/kubesearch-mcp datasource=docker
  image: ghcr.io/perfectra1n/kubesearch-mcp:sha-405e7b2
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
