---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-postgres
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-postgres datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-postgres:v0.1.0
  transport: sse
  secrets:
    - name: mcp-postgres-secret
      key: POSTGRES_SUPERPASS
      targetEnvName: POSTGRES_PASSWORD
