---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-kubernetes
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-kubernetes datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-kubernetes:v0.1.0
  transport: sse
