---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-forgejo
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-forgejo datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-forgejo:v0.1.0
  transport: sse
  secrets:
    - name: mcp-forgejo-secret
      key: FORGEJO_TOKEN
      targetEnvName: FORGEJO_TOKEN
