---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-grafana
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/grafana/mcp-grafana datasource=docker
  image: docker.io/grafana/mcp-grafana:1.2.0@sha256:cfae68f893dbe40cb6df69579f78beb226f973ded4436d47c844f91d2f00dc53
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  args:
    - "-t"
    - "stdio"
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.monitoring.svc.cluster.local:3000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
