---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-kubesearch
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=ghcr.io/perfectra1n/kubesearch-mcp datasource=docker
  image: ghcr.io/perfectra1n/kubesearch-mcp:1.0.1@sha256:a8e2129500321b491893e08700d6f87fe8f9078efbea546e0ba8d5183c127df1
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
