---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-github
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=ghcr.io/github/github-mcp-server datasource=docker
  image: ghcr.io/github/github-mcp-server:v1.7.0
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  secrets:
    - name: mcp-github-secret
      key: GITHUB_TOKEN
      targetEnvName: GITHUB_PERSONAL_ACCESS_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
