---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-grafana
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/grafana/mcp-grafana datasource=docker
  image: docker.io/grafana/mcp-grafana:1.1.0@sha256:f21a19cebbfa7c3a76ef1746171e5ffc3601064e432f593e7c6cb526e5216e5f
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  args:
    - "-t"
    - "stdio"
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.monitoring.svc.cluster.local:3000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
