---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-arr-stack
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-arr-stack datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-arr-stack:v0.1.0
  transport: sse
  secrets:
    - name: mcp-arr-secret
      key: SONARR_APIKEY
      targetEnvName: SONARR_API_KEY
    - name: mcp-arr-secret
      key: RADARR_APIKEY
      targetEnvName: RADARR_API_KEY
    - name: mcp-arr-secret
      key: PROWLARR_APIKEY
      targetEnvName: PROWLARR_API_KEY
