---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-github
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/node datasource=docker
  image: docker.io/node:24-alpine
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  secrets:
    - name: mcp-github-secret
      key: GITHUB_TOKEN
      targetEnvName: GITHUB_PERSONAL_ACCESS_TOKEN
  env:
    - name: HOME
      value: /tmp
    - name: NPM_CONFIG_CACHE
      value: /tmp/.npm
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: mcp
          image: docker.io/node:24-alpine
          command:
            - npx
          args:
            - -y
            - "@modelcontextprotocol/server-github@2025.4.8"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
