---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=docker.io/isokoliuk/mcp-searxng datasource=docker
  image: docker.io/isokoliuk/mcp-searxng:2.1.0@sha256:b4cf227a6459a5071a9b455c060bdd6912ee4fd4d2275abfdb30bc4f9e539136
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.ai.svc.cluster.local:8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
