---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-kyverno
spec:
  # renovate: depName=ghcr.io/stacklok/toolhive/mcp-kyverno datasource=docker
  image: ghcr.io/stacklok/toolhive/mcp-kyverno:v0.1.0
  transport: sse
