---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-home-assistant
spec:
  # renovate: depName=ghcr.io/homeassistant-ai/ha-mcp datasource=docker
  image: ghcr.io/homeassistant-ai/ha-mcp:2.3.1
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.household.svc.cluster.local:8123
  secrets:
    - name: mcp-home-assistant-secret
      key: HOMEASSISTANT_TOKEN
      targetEnvName: HOMEASSISTANT_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
