---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-memory
spec:
  groupRef:
    name: toolhive-servers
  # renovate: depName=ghcr.io/bjw-s-labs/mcp-memory datasource=docker
  image: ghcr.io/bjw-s-labs/mcp-memory:2026.8.31@sha256:81f1ec66d6c771a516f47705a827b6ac7400e197b4f48b487c3488ee68f2f72d
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
