---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: toolhive-gateway
spec:
  groupRef:
    name: toolhive-servers
  incomingAuth:
    type: anonymous
  config:
    aggregation:
      conflictResolution: priority
      conflictResolutionConfig:
        priorityOrder:
          - mcp-kubernetes
          - mcp-github
          - mcp-memory
          - mcp-flux
          - mcp-home-assistant
          - mcp-arr-stack
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
