---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-hub-secrets
  namespace: networking
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: towonel-hub-secrets
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        # Postgres Init Container Credentials
        INIT_POSTGRES_DBNAME: "towonel"
        INIT_POSTGRES_HOST: "postgres17-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # Official Towonel Hub Configuration
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        TOWONEL_HUB_DB_DRIVER: "postgres"
        TOWONEL_HUB_DB_DSN: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.databases.svc.cluster.local:5432/towonel?sslmode=disable"
        TOWONEL_HUB_WEB_ENABLED: "true"
        TOWONEL_HUB_PUBLIC_URL: "https://towonel-hub.${SECRET_DOMAIN}"
        TOWONEL_HUB_OIDC_CODEBERG_ISSUER: "https://id.${SECRET_DOMAIN}"
        TOWONEL_HUB_OIDC_CODEBERG_REDIRECT_URI: "https://towonel.home.${SECRET_DOMAIN}/api/v1/auth/oidc/codeberg/callback"
        TOWONEL_HUB_OIDC_CODEBERG_TRUST_EMAIL_VERIFIED: "true"

        # Mailer Configuration
        TOWONEL_MAIL_MAILJET_API_KEY: "disabled"
        TOWONEL_MAIL_MAILJET_API_SECRET: "disabled"
        TOWONEL_MAIL_FROM_EMAIL: "towonel@${SECRET_DOMAIN}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Towonel DB Credentials"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "Towonel DB Credentials"
        property: "password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-hub-fields
  namespace: networking
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: towonel-hub-secrets
    creationPolicy: Merge
  data:
    - secretKey: TOWONEL_IDENTITY_KEY
      remoteRef:
        key: "Towonel Service Credentials"
        property: "NODE_IDENTITY_KEY"
    - secretKey: TOWONEL_HUB_OPERATOR_API_KEY
      remoteRef:
        key: "Towonel Service Credentials"
        property: "OPERATOR_API_KEY"
    - secretKey: TOWONEL_HUB_KEK
      remoteRef:
        key: "Towonel Service Credentials"
        property: "HUB_KEK"
    - secretKey: TOWONEL_INVITE_HASH_KEY
      remoteRef:
        key: "Towonel Service Credentials"
        property: "INVITE_HASH_KEY"
    - secretKey: TOWONEL_HUB_LINK_PSK
      remoteRef:
        key: "Towonel Service Credentials"
        property: "HUB_LINK_PSK"
