kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ii+t/fze35p2SZlTgnmB8w==,iv:lTGA2oGltx7s+J4/Y9Fo1Wu1fwik3snKAVsNwvjJVIQ=,tag:VuE8VLzz2EwFx1USv4zt/w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:iEUnSAf89xNNaG8ofZFFoHzLVOfjw8Pg94HjxBHVOoo=,iv:NM2wPFb8ZPDFeAlYUpbt09ksY/hiOFTJMhzjqM1THQw=,tag:CQpGj56A+R9DQzttjVvhYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUFRNd3BVWG9iMGcxWVBR
            UmNGc285NXloY1lCUXQxQndNVHNGQXovQmdjClRXei9pN093aFg3czdjbGlneFVy
            Y0p3ZTIxM04vRXFyQ3loVHd3N294c2sKLS0tIE1kczAvQ05qbVM3YUdmT3BvT2NM
            elNIbzhCanFyNks0Wk1iUTZDNkJEWUEKa32Llh0Ig/j1HKo6Fzp4is8T9MuwvGLl
            BLNE+iAeOanRk6JdARFfXyCZkcqcoVcwv4q73ot3Wbi/P1NGW1+SkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ls774hqamu0vgl65vwxrfu2tqm6h7p7pj9k6gagcpluxllypfwsk3hqzm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T16:11:33Z"
    mac: ENC[AES256_GCM,data:XE/znHw9CWjuTgfEGJ8PME+wXdVld5oTBkivyfXFSqDv6qUo/TaghqItPG1UgleLbsd9ESPMchHmgTD4qKaF5BX0ytslORun2HCk9MJhqd+kblFPGqaZDqTyQNj+PX62v0mlI1O8PIzesyHHbKe6nxRVvketvf/i0B/HRLZImo4=,iv:GO7ogEC4+poFZZNFJVpLw7n7ZTseRfrgwVJX9+9tqBs=,tag:Jx3Z2jEF/Sg7ApkHG3V9BQ==,type:str]
    version: 3.13.3
