---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ceph
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Ceph
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: flux
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Flux
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Kubernetes
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: postgres
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Postgres
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: traefik
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Traefik
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: unifi
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Unifi
