apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        nodePlugin:
          priorityClassName: system-node-critical
        controllerPlugin:
          priorityClassName: system-cluster-critical
        enableMetadata: true
        snapshotPolicy: volumeSnapshot
        kernelMountOptions:
          ms_mode: prefer-crc

    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
        nodePlugin:
          resources:
            registrar:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            liveness:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            logRotator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            plugin:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            addons:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
        controllerPlugin:
          resources:
            attacher:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            snapshotter:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            resizer:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            provisioner:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            omapGenerator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            liveness:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            logRotator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            plugin:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            addons:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        nodePlugin:
          resources:
            registrar:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            liveness:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            logRotator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            plugin:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
            addons:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
        controllerPlugin:
          resources:
            attacher:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            snapshotter:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            resizer:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            provisioner:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            omapGenerator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            liveness:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            logRotator:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            plugin:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            addons:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
      nfs:
        enabled: false
      nvmeof:
        enabled: false
