---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: minio
spec:
  name: MinIO
  launchUrl: https://minio.home.${SECRET_DOMAIN}/
  callbackUrls:
    - https://minio.home.${SECRET_DOMAIN}/oauth_callback
  logoutCallbackUrls:
    - https://minio.home.${SECRET_DOMAIN}/
  allowedUserGroups:
    - name: admin
      namespace: auth
  secret:
    name: minio-oidc-credentials
    keys:
      clientID: MINIO_IDENTITY_OPENID_CLIENT_ID
      clientSecret: MINIO_IDENTITY_OPENID_CLIENT_SECRET
