apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - audiobookshelf/ks.yaml
  - bazarr/ks.yaml
  - isponsorblocktv/ks.yaml
  - jellyfin/ks.yaml
  - lidarr/ks.yaml
  - ombi/ks.yaml
  - plex/ks.yaml
  - profilarr/ks.yaml
  - radarr/ks.yaml
  - readarr-audio/ks.yaml
  - readarr-books/ks.yaml
  - sonarr/ks.yaml
  - tautulli/ks.yaml
  - tdarr-node/ks.yaml
  - tdarr-server/ks.yaml
  - watchstate/ks.yaml
