machine:
  type: controlplane
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.model == "PNY CS2241 1TB SSD"
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: node3.home
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
addresses:
  - address: 10.0.1.53/23
