---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toolhive-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: toolhive-operator
  endpoints:
    - port: metrics
      interval: 30s
