---
serviceMonitor:
  create: true
web:
  config:
    baseURL: https://flux-ui.home.${SECRET_DOMAIN}
    authentication:
      type: OAuth2
      oauth2:
        provider: OIDC
        issuerURL: https://id.${SECRET_DOMAIN}
        scopes:
          - openid
          - profile
          - email
          - groups
  rbac:
    createRoles: true
  networkPolicy:
    create: false
  ingress:
    enabled: false
