---
serviceMonitor:
  create: true
web:
  config:
    authentication:
      type: Anonymous
      anonymous:
        username: flux
        groups:
          - flux-admin
  rbac:
    createRoles: true
  networkPolicy:
    create: false
  ingress:
    enabled: false
