apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-tunnel-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: ingress-tunnel-secrets
    template:
      data:
        hcloud_token: "{{ .hcloud_token }}"
        ovh_endpoint: "{{ .ovh_endpoint }}"
        ovh_application_key: "{{ .ovh_application_key }}"
        ovh_application_secret: "{{ .ovh_application_secret }}"
        ovh_consumer_key: "{{ .ovh_consumer_key }}"
        ovh_service_name: "{{ .ovh_service_name }}"
        smtp_server: "{{ .smtp_server }}"
        smtp_username: "{{ .smtp_username }}"
        smtp_password: "{{ .smtp_password }}"
        admin_username: "admin"
        netbird_selfhosted_setup_key: "{{ .netbird_selfhosted_setup_key }}"
        netbird_relay_auth_secret: "{{ .netbird_relay_auth_secret }}"
        netbird_api_token: "{{ .netbird_api_token }}"
        peer_us_private_key: "{{ .peer1_private_key }}"
        peer_us_public_key: "{{ .peer1_public_key }}"
        peer_eu_private_key: "{{ .peer2_private_key }}"
        peer_eu_public_key: "{{ .peer2_public_key }}"
        wg_public_key: "{{ .wg_public_key }}"
  refreshInterval: 15m
  data:
    - secretKey: hcloud_token
      remoteRef:
        key: "Hetzner Credentials"
        property: tofu_api_token
    - secretKey: ovh_endpoint
      remoteRef:
        key: "OVH Credentials"
        property: endpoint
    - secretKey: ovh_application_key
      remoteRef:
        key: "OVH Credentials"
        property: application_key
    - secretKey: ovh_application_secret
      remoteRef:
        key: "OVH Credentials"
        property: application_secret
    - secretKey: ovh_consumer_key
      remoteRef:
        key: "OVH Credentials"
        property: consumer_key
    - secretKey: ovh_service_name
      remoteRef:
        key: "OVH Credentials"
        property: service_name
    - secretKey: smtp_server
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-server"
    - secretKey: smtp_username
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-username"
    - secretKey: smtp_password
      remoteRef:
        key: "Mailgun Credentials"
        property: "smtp-password"
    - secretKey: netbird_selfhosted_setup_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "VPS_SELFHOSTED_SETUP_KEY"
    - secretKey: netbird_relay_auth_secret
      remoteRef:
        key: "Netbird Service Credentials"
        property: "RELAY_AUTH_SECRET"
    - secretKey: netbird_api_token
      remoteRef:
        key: "Netbird Service Credentials"
        property: "NB_SELFHOSTED_API_KEY"
    - secretKey: peer1_private_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "PEER1_PRIVATE_KEY"
    - secretKey: peer1_public_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "PEER1_PUBLIC_KEY"
    - secretKey: peer2_private_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "PEER2_PRIVATE_KEY"
    - secretKey: peer2_public_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "PEER2_PUBLIC_KEY"
    - secretKey: wg_public_key
      remoteRef:
        key: "Netbird Service Credentials"
        property: "WG_PUBLIC_KEY"
