apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tofu.yaml
  - external-secret.yaml
  - gitrepo.yaml
  - rbac.yaml
  - vps-direct-route.yaml
  - health-responder.yaml
  - dashboard.yaml
