---
apiVersion: v1
kind: Service
metadata:
  name: towonel-agent
  namespace: networking
  labels:
    app.kubernetes.io/name: towonel-agent
    app.kubernetes.io/instance: towonel-agent
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: towonel-agent
