---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: forgejo-db
    template:
      data:
        INIT_POSTGRES_DBNAME: "forgejo"
        INIT_POSTGRES_HOST: "postgres16-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App database credentials:
        FORGEJO_DATABASE_USER: "{{ .POSTGRES_USER }}"
        FORGEJO_DATABASE_PASSWORD: "{{ .POSTGRES_PASS }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "${BW_POSTGRES_SUPERUSER}"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "${BW_FORGEJO_CREDENTIALS}"
        property: "username"
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: "${BW_FORGEJO_CREDENTIALS}"
        property: "password"
