---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app speakr
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: *app
    template:
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost "${POSTGRES_HOST}"
        INIT_POSTGRES_DBNAME: speakr
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@${POSTGRES_HOST}/speakr"
        SECRET_KEY: "{{ .SECRET_KEY }}"
        HF_TOKEN: "{{ .HF_TOKEN }}"
  data:
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "username"
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: "Postgres SuperUser Credentials"
        property: "password"
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "Speakr Credentials"
        property: "username"
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "Speakr Credentials"
        property: "password"
    - secretKey: SECRET_KEY
      remoteRef:
        key: "Speakr Credentials"
        property: "SECRET_KEY"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: HF_TOKEN
      remoteRef:
        key: "Speakr Credentials"
        property: "HF_TOKEN"
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
