---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: speakr
spec:
  name: Speakr
  launchUrl: https://speakr.home.${SECRET_DOMAIN}/
  logo:
    logoUrl: https://raw.githubusercontent.com/murtaza-nasir/speakr/master/static/img/icon-512x512.png
  callbackUrls:
    - https://speakr.home.${SECRET_DOMAIN}/auth/sso/callback
  allowedUserGroups:
    - name: users
      namespace: auth
  secret:
    name: speakr-oidc-credentials
    keys:
      clientID: SSO_CLIENT_ID
      clientSecret: SSO_CLIENT_SECRET
      discoveryUrl: SSO_DISCOVERY_URL
