# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app odysseus
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: ollama
    - name: searxng
    - name: ntfy
    - name: chromadb
    - name: volsync
  path: ./cluster/apps/ai/odysseus/app
  components:
    - ../../../../templates/volsync/primary
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_NFS_START_MINUTE: "26"
      VOLSYNC_B2_START_MINUTE: "51"
  retryInterval: 2m
