apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rathole-infra-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: rathole-infra-secrets
    template:
      data:
        hcloud_token: "{{ .hcloud_token }}"
        rathole_handshake_token: "{{ .rathole_handshake_token }}"
        rathole_service_token: "{{ .rathole_service_token }}"
  refreshInterval: 15m
  data:
    - secretKey: hcloud_token
      remoteRef:
        key: "${BW_HETZNER}"
        property: tofu_api_token
    - secretKey: rathole_handshake_token
      remoteRef:
        key: "${BW_RATHOLE}"
        property: handshake_token
    - secretKey: rathole_service_token
      remoteRef:
        key: "${BW_RATHOLE}"
        property: service_token
