apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tofu-infra-git
  namespace: networking
spec:
  interval: 30m
  url: https://github.com/mrwulf/home-cluster.git
  ref:
    branch: main
