---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # Currently no way to detect automatically
  DEFAULT_BRANCH: main
  MISE_MINIMUM_RELEASE_AGE: 0s

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Run all tests
        run: mise exec -- task test:all
