---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: trek
spec:
  name: TREK
  launchUrl: https://trip.${SECRET_DOMAIN}/
  callbackUrls:
    - https://trip.${SECRET_DOMAIN}/api/auth/oidc/callback
  logoutCallbackUrls:
    - https://trip.${SECRET_DOMAIN}/
  allowedUserGroups:
    - name: users
      namespace: auth
    - name: admin
      namespace: auth
  pkceEnabled: true
  secret:
    name: trek-oidc-credentials
    keys:
      clientID: OIDC_CLIENT_ID
      clientSecret: OIDC_CLIENT_SECRET
      issuerUrl: OIDC_ISSUER
